# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

# 添加信息对话框员工编号过滤器
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

from PyQt5 import QtCore, QtGui, QtWidgets

from . import page_rc
# import page_rc

class Ui_Page(object):
	def setupUi(self, Page):
		Page.setObjectName("Page")
		Page.resize(1040, 640)
		self.gridLayout = QtWidgets.QGridLayout(Page)
		self.gridLayout.setObjectName("gridLayout")
		self.groupBox_1 = QtWidgets.QGroupBox(Page)
		self.groupBox_1.setObjectName("groupBox_1")
		self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.groupBox_1)
		self.horizontalLayout_1.setObjectName("horizontalLayout_1")
		self.global_search = QtWidgets.QLineEdit(self.groupBox_1)
		self.global_search.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.global_search.setFrame(True)
		self.global_search.setClearButtonEnabled(True)
		self.global_search.setObjectName("global_search")
		self.horizontalLayout_1.addWidget(self.global_search)
		self.line = QtWidgets.QFrame(self.groupBox_1)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_1.addWidget(self.line)
		self.search_field = QtWidgets.QComboBox(self.groupBox_1)
		self.search_field.setObjectName("search_field")
		self.horizontalLayout_1.addWidget(self.search_field)
		self.partial_search = QtWidgets.QLineEdit(self.groupBox_1)
		self.partial_search.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.partial_search.setFrame(True)
		self.partial_search.setClearButtonEnabled(True)
		self.partial_search.setObjectName("partial_search")
		self.horizontalLayout_1.addWidget(self.partial_search)
		self.gridLayout.addWidget(self.groupBox_1, 0, 0, 1, 1)
		self.groupBox_2 = QtWidgets.QGroupBox(Page)
		self.groupBox_2.setObjectName("groupBox_2")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.editable = QtWidgets.QRadioButton(self.groupBox_2)
		self.editable.setFocusPolicy(QtCore.Qt.NoFocus)
		self.editable.setChecked(True)
		self.editable.setObjectName("editable")
		self.horizontalLayout_2.addWidget(self.editable)
		self.uneditable = QtWidgets.QRadioButton(self.groupBox_2)
		self.uneditable.setFocusPolicy(QtCore.Qt.NoFocus)
		self.uneditable.setObjectName("uneditable")
		self.horizontalLayout_2.addWidget(self.uneditable)
		self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
		self.groupBox_3 = QtWidgets.QGroupBox(Page)
		self.groupBox_3.setObjectName("groupBox_3")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.submit = QtWidgets.QPushButton(self.groupBox_3)
		self.submit.setFocusPolicy(QtCore.Qt.NoFocus)
		self.submit.setObjectName("submit")
		self.horizontalLayout_3.addWidget(self.submit)
		self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
		self.groupBox_4 = QtWidgets.QGroupBox(Page)
		self.groupBox_4.setObjectName("groupBox_4")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.title = QtWidgets.QLabel(self.groupBox_4)
		self.title.setStyleSheet("background-color: rgb(200, 200, 200);")
		self.title.setAlignment(QtCore.Qt.AlignCenter)
		self.title.setMinimumHeight(30)
		self.title.setObjectName("title")
		self.verticalLayout_4.addWidget(self.title)
		self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
		self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
		self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
		self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
		self.tableWidget.setCornerButtonEnabled(False)
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.setColumnCount(0)
		self.tableWidget.setRowCount(0)
		self.verticalLayout_4.addWidget(self.tableWidget)
		self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 3)
		self.info_form_page_bar = QtWidgets.QWidget(Page)
		self.info_form_page_bar.setObjectName("info_form_page_bar")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.info_form_page_bar)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.form_first_page = QtWidgets.QPushButton(self.info_form_page_bar)
		self.form_first_page.setFocusPolicy(QtCore.Qt.NoFocus)
		self.form_first_page.setObjectName("form_first_page")
		self.horizontalLayout_4.addWidget(self.form_first_page)
		self.form_previous_page = QtWidgets.QPushButton(self.info_form_page_bar)
		self.form_previous_page.setFocusPolicy(QtCore.Qt.NoFocus)
		self.form_previous_page.setObjectName("form_previous_page")
		self.horizontalLayout_4.addWidget(self.form_previous_page)
		self.form_page_num = QtWidgets.QLabel(self.info_form_page_bar)
		self.form_page_num.setAlignment(QtCore.Qt.AlignCenter)
		self.form_page_num.setObjectName("form_page_num")
		self.horizontalLayout_4.addWidget(self.form_page_num)
		self.form_next_page = QtWidgets.QPushButton(self.info_form_page_bar)
		self.form_next_page.setFocusPolicy(QtCore.Qt.NoFocus)
		self.form_next_page.setObjectName("form_next_page")
		self.horizontalLayout_4.addWidget(self.form_next_page)
		self.form_last_page = QtWidgets.QPushButton(self.info_form_page_bar)
		self.form_last_page.setFocusPolicy(QtCore.Qt.NoFocus)
		self.form_last_page.setObjectName("form_last_page")
		self.horizontalLayout_4.addWidget(self.form_last_page)
		self.gridLayout.addWidget(self.info_form_page_bar, 2, 0, 1, 3)

		self.retranslateUi(Page)
		QtCore.QMetaObject.connectSlotsByName(Page)

	def retranslateUi(self, Page):
		_translate = QtCore.QCoreApplication.translate
		Page.setWindowTitle(_translate("Page", "Form"))
		self.groupBox_1.setTitle(_translate("Page", "表格搜索"))
		self.global_search.setPlaceholderText(_translate("Page", "全局搜索"))
		self.partial_search.setPlaceholderText(_translate("Page", "部分搜索"))
		self.groupBox_2.setTitle(_translate("Page", "表格状态"))
		self.editable.setText(_translate("Page", "可编辑"))
		self.uneditable.setText(_translate("Page", "不可编辑"))
		self.groupBox_3.setTitle(_translate("Page", "表格操作"))
		self.submit.setText(_translate("Page", "提交"))
		self.groupBox_4.setTitle(_translate("Page", "XXX公司"))
		self.title.setText(_translate("Page", "员工信息表"))
		self.form_first_page.setText(_translate("Page", "首页"))
		self.form_previous_page.setText(_translate("Page", "上一页"))
		self.form_page_num.setText(_translate("Page", "[1/5]页"))
		self.form_next_page.setText(_translate("Page", "下一页"))
		self.form_last_page.setText(_translate("Page", "尾页"))


class Ui_AddEmpInfoDialog(object):
	def setupUi(self, AddEmpInfoDialog):
		AddEmpInfoDialog.setObjectName("AddEmpInfoDialog")
		AddEmpInfoDialog.resize(669, 503)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/form/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		AddEmpInfoDialog.setWindowIcon(icon)
		AddEmpInfoDialog.setStyleSheet("QGroupBox {\n"
"	background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"									  stop: 0 #E0E0E0, stop: 1 #c8c8c8);\n"
"	border: 2px solid gray;\n"
"	border-radius: 5px;\n"
"	margin-top: 1.5ex;\n"
"}\n"
"QGroupBox::title {\n"
"	subcontrol-origin: margin;\n"
"	left: 15px;\n"
"}\n"
"QPushButton {\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.161765 rgba(165, 216, 255, 255), stop:1 rgba(0, 157, 255, 255));\n"
"\n"
"	border-style:outset;\n"
" \n"
"	border-width:2px;\n"
"\n"
"	border-color:#0055ff;\n"
"\n"
"	border-radius:10px;\n"
"\n"
"	min-width:100px;\n"
"\n"
"	min-height:20px;\n"
"\n"
"	padding:4px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.161765 rgba(120, 197, 255, 255), stop:1 rgba(0, 149, 242, 255));\n"
"	\n"
"	border-style:inset;\n"
"\n"
"	padding-left:6px;\n"
"\n"
"	padding-top:6px;\n"
"}\n"
"QLineEdit {\n"
"	height: 20px;\n"
"	border: 2px solid gray;\n"
"	border-radius: 10px;\n"
"	padding: 0 8px;\n"
"	background: lightBlue;\n"
"	selection-background-color: darkgray;\n"
"}\n"
"QPlainTextEdit {\n"
"	border: 2px solid gray;\n"
"	border-radius: 10px;\n"
"	background-color: lightBlue;\n"
"}\n"
"QSpinBox {\n"
"	border: 2px solid gray;\n"
"	background-color: lightBlue;\n"
"}")
		self.verticalLayout = QtWidgets.QVBoxLayout(AddEmpInfoDialog)
		self.verticalLayout.setObjectName("verticalLayout")
		self.company = QtWidgets.QGroupBox(AddEmpInfoDialog)
		self.company.setObjectName("company")
		self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.company)
		self.verticalLayout_10.setSpacing(21)
		self.verticalLayout_10.setObjectName("verticalLayout_10")
		self.title = QtWidgets.QLabel(self.company)
		self.title.setStyleSheet("background-color: rgb(200, 200, 200);")
		self.title.setAlignment(QtCore.Qt.AlignCenter)
		self.title.setMinimumHeight(30)
		self.title.setObjectName("title")
		self.verticalLayout_10.addWidget(self.title)
		self.widget_emp_info = QtWidgets.QWidget(self.company)
		self.widget_emp_info.setObjectName("widget_emp_info")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_emp_info)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setHorizontalSpacing(21)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.widget_sex = QtWidgets.QWidget(self.widget_emp_info)
		self.widget_sex.setObjectName("widget_sex")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_sex)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.male = QtWidgets.QRadioButton(self.widget_sex)
		self.male.setFocusPolicy(QtCore.Qt.NoFocus)
		self.male.setChecked(True)
		self.male.setObjectName("male")
		self.horizontalLayout.addWidget(self.male)
		self.female = QtWidgets.QRadioButton(self.widget_sex)
		self.female.setFocusPolicy(QtCore.Qt.NoFocus)
		self.female.setObjectName("female")
		self.horizontalLayout.addWidget(self.female)
		self.gridLayout_2.addWidget(self.widget_sex, 1, 1, 1, 1)
		self.label_department = QtWidgets.QLabel(self.widget_emp_info)
		self.label_department.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_department.setObjectName("label_department")
		self.gridLayout_2.addWidget(self.label_department, 3, 0, 1, 1)
		self.label_home_address = QtWidgets.QLabel(self.widget_emp_info)
		self.label_home_address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_home_address.setObjectName("label_home_address")
		self.gridLayout_2.addWidget(self.label_home_address, 8, 0, 1, 1)
		self.department = QtWidgets.QComboBox(self.widget_emp_info)
		self.department.setObjectName("department")
		self.department.addItem("")
		self.department.addItem("")
		self.department.addItem("")
		self.department.addItem("")
		self.gridLayout_2.addWidget(self.department, 3, 1, 1, 1)
		self.label_entry_time = QtWidgets.QLabel(self.widget_emp_info)
		self.label_entry_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_entry_time.setObjectName("label_entry_time")
		self.gridLayout_2.addWidget(self.label_entry_time, 6, 0, 1, 1)
		self.label_position = QtWidgets.QLabel(self.widget_emp_info)
		self.label_position.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_position.setObjectName("label_position")
		self.gridLayout_2.addWidget(self.label_position, 3, 2, 1, 1)
		self.home_address = QtWidgets.QLineEdit(self.widget_emp_info)
		self.home_address.setObjectName("home_address")
		self.gridLayout_2.addWidget(self.home_address, 8, 1, 1, 4)
		self.position = QtWidgets.QComboBox(self.widget_emp_info)
		self.position.setObjectName("position")
		self.position.addItem("")
		self.position.addItem("")
		self.position.addItem("")
		self.position.addItem("")
		self.position.addItem("")
		self.position.addItem("")
		self.position.addItem("")
		self.gridLayout_2.addWidget(self.position, 3, 3, 1, 1)
		self.ID_card = QtWidgets.QLineEdit(self.widget_emp_info)
		self.ID_card.setObjectName("ID_card")
		self.gridLayout_2.addWidget(self.ID_card, 5, 1, 1, 1)
		self.photo = QtWidgets.QLabel(self.widget_emp_info)
		self.photo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.photo.setStyleSheet("border: 1px solid gray;\n"
"padding: 3px\n"
"")
		self.photo.setPixmap(QtGui.QPixmap(":/form/images/default_avatar.png"))
		self.photo.setScaledContents(True)
		self.photo.setObjectName("photo")
		self.gridLayout_2.addWidget(self.photo, 0, 4, 4, 1)
		self.label_educational_background = QtWidgets.QLabel(self.widget_emp_info)
		self.label_educational_background.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_educational_background.setObjectName("label_educational_background")
		self.gridLayout_2.addWidget(self.label_educational_background, 2, 2, 1, 1)
		self.educational_background = QtWidgets.QComboBox(self.widget_emp_info)
		self.educational_background.setObjectName("educational_background")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.educational_background.addItem("")
		self.gridLayout_2.addWidget(self.educational_background, 2, 3, 1, 1)
		self.label_sex = QtWidgets.QLabel(self.widget_emp_info)
		self.label_sex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_sex.setObjectName("label_sex")
		self.gridLayout_2.addWidget(self.label_sex, 1, 0, 1, 1)
		self.label_phone = QtWidgets.QLabel(self.widget_emp_info)
		self.label_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_phone.setObjectName("label_phone")
		self.gridLayout_2.addWidget(self.label_phone, 2, 0, 1, 1)
		self.label_age = QtWidgets.QLabel(self.widget_emp_info)
		self.label_age.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_age.setObjectName("label_age")
		self.gridLayout_2.addWidget(self.label_age, 1, 2, 1, 1)
		self.phone = QtWidgets.QLineEdit(self.widget_emp_info)
		self.phone.setObjectName("phone")
		self.gridLayout_2.addWidget(self.phone, 2, 1, 1, 1)
		self.label_ID_card = QtWidgets.QLabel(self.widget_emp_info)
		self.label_ID_card.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_ID_card.setObjectName("label_ID_card")
		self.gridLayout_2.addWidget(self.label_ID_card, 5, 0, 1, 1)
		self.graduated_school = QtWidgets.QLineEdit(self.widget_emp_info)
		self.graduated_school.setObjectName("graduated_school")
		self.gridLayout_2.addWidget(self.graduated_school, 7, 1, 1, 4)
		self.label_graduated_school = QtWidgets.QLabel(self.widget_emp_info)
		self.label_graduated_school.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_graduated_school.setObjectName("label_graduated_school")
		self.gridLayout_2.addWidget(self.label_graduated_school, 7, 0, 1, 1)
		self.name = PromptLineEdit(self.widget_emp_info)
		self.name.setObjectName("name")
		self.gridLayout_2.addWidget(self.name, 0, 3, 1, 1)
		self.label_name = QtWidgets.QLabel(self.widget_emp_info)
		self.label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_name.setObjectName("label_name")
		self.gridLayout_2.addWidget(self.label_name, 0, 2, 1, 1)
		self.label_number = QtWidgets.QLabel(self.widget_emp_info)
		self.label_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_number.setObjectName("label_number")
		self.gridLayout_2.addWidget(self.label_number, 0, 0, 1, 1)
		self.number = PromptLineEdit(self.widget_emp_info)
		self.number.setObjectName("number")
		self.number.textFiltering()
		self.gridLayout_2.addWidget(self.number, 0, 1, 1, 1)
		self.widget_entry_time = QtWidgets.QWidget(self.widget_emp_info)
		self.widget_entry_time.setObjectName("widget_entry_time")
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_entry_time)
		self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.year = QtWidgets.QSpinBox(self.widget_entry_time)
		self.year.setMinimum(2017)
		self.year.setMaximum(2100)
		self.year.setObjectName("year")
		self.horizontalLayout_9.addWidget(self.year)
		self.label_year = QtWidgets.QLabel(self.widget_entry_time)
		self.label_year.setAlignment(QtCore.Qt.AlignCenter)
		self.label_year.setObjectName("label_year")
		self.horizontalLayout_9.addWidget(self.label_year)
		self.month = QtWidgets.QSpinBox(self.widget_entry_time)
		self.month.setMinimum(1)
		self.month.setMaximum(12)
		self.month.setObjectName("month")
		self.horizontalLayout_9.addWidget(self.month)
		self.label_month = QtWidgets.QLabel(self.widget_entry_time)
		self.label_month.setAlignment(QtCore.Qt.AlignCenter)
		self.label_month.setObjectName("label_month")
		self.horizontalLayout_9.addWidget(self.label_month)
		self.day = QtWidgets.QSpinBox(self.widget_entry_time)
		self.day.setMinimum(1)
		self.day.setMaximum(31)
		self.day.setObjectName("day")
		self.horizontalLayout_9.addWidget(self.day)
		self.label_day = QtWidgets.QLabel(self.widget_entry_time)
		self.label_day.setAlignment(QtCore.Qt.AlignCenter)
		self.label_day.setObjectName("label_day")
		self.horizontalLayout_9.addWidget(self.label_day)
		self.gridLayout_2.addWidget(self.widget_entry_time, 6, 1, 1, 2)
		self.widget_age = QtWidgets.QWidget(self.widget_emp_info)
		self.widget_age.setObjectName("widget_age")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_age)
		self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.age = QtWidgets.QSpinBox(self.widget_age)
		self.age.setMinimum(16)
		self.age.setMaximum(100)
		self.age.setProperty("value", 20)
		self.age.setObjectName("age")
		self.horizontalLayout_2.addWidget(self.age)
		self.label_year_old = QtWidgets.QLabel(self.widget_age)
		self.label_year_old.setObjectName("label_year_old")
		self.horizontalLayout_2.addWidget(self.label_year_old)
		self.horizontalLayout_2.setStretch(0, 1)
		self.gridLayout_2.addWidget(self.widget_age, 1, 3, 1, 1)
		self.verticalLayout_10.addWidget(self.widget_emp_info)
		self.widget_personal_profile = QtWidgets.QWidget(self.company)
		self.widget_personal_profile.setObjectName("widget_personal_profile")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_personal_profile)
		self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.label_personal_profile = QtWidgets.QLabel(self.widget_personal_profile)
		self.label_personal_profile.setObjectName("label_personal_profile")
		self.verticalLayout_5.addWidget(self.label_personal_profile)
		self.personal_profile = QtWidgets.QPlainTextEdit(self.widget_personal_profile)
		self.personal_profile.setFrameShadow(QtWidgets.QFrame.Plain)
		self.personal_profile.setPlainText("")
		self.personal_profile.setObjectName("personal_profile")
		self.verticalLayout_5.addWidget(self.personal_profile)
		self.verticalLayout_10.addWidget(self.widget_personal_profile)
		self.verticalLayout.addWidget(self.company)
		self.widget_btn = QtWidgets.QWidget(AddEmpInfoDialog)
		self.widget_btn.setObjectName("widget_btn")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_btn)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem)
		self.add = QtWidgets.QPushButton(self.widget_btn)
		self.add.setFocusPolicy(QtCore.Qt.NoFocus)
		self.add.setObjectName("add")
		self.horizontalLayout_5.addWidget(self.add)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem1)
		self.cancel = QtWidgets.QPushButton(self.widget_btn)
		self.cancel.setFocusPolicy(QtCore.Qt.NoFocus)
		self.cancel.setObjectName("cancel")
		self.horizontalLayout_5.addWidget(self.cancel)
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem2)
		self.verticalLayout.addWidget(self.widget_btn)

		self.retranslateUi(AddEmpInfoDialog)
		QtCore.QMetaObject.connectSlotsByName(AddEmpInfoDialog)
		AddEmpInfoDialog.setTabOrder(self.number, self.name)
		AddEmpInfoDialog.setTabOrder(self.name, self.age)
		AddEmpInfoDialog.setTabOrder(self.age, self.phone)
		AddEmpInfoDialog.setTabOrder(self.phone, self.ID_card)
		AddEmpInfoDialog.setTabOrder(self.ID_card, self.year)
		AddEmpInfoDialog.setTabOrder(self.year, self.month)
		AddEmpInfoDialog.setTabOrder(self.month, self.day)
		AddEmpInfoDialog.setTabOrder(self.day, self.graduated_school)
		AddEmpInfoDialog.setTabOrder(self.graduated_school, self.home_address)
		AddEmpInfoDialog.setTabOrder(self.home_address, self.personal_profile)
		AddEmpInfoDialog.setTabOrder(self.personal_profile, self.educational_background)
		AddEmpInfoDialog.setTabOrder(self.educational_background, self.department)
		AddEmpInfoDialog.setTabOrder(self.department, self.position)

	def retranslateUi(self, AddEmpInfoDialog):
		_translate = QtCore.QCoreApplication.translate
		AddEmpInfoDialog.setWindowTitle(_translate("AddEmpInfoDialog", "添加员工信息"))
		self.company.setTitle(_translate("AddEmpInfoDialog", "XXX公司"))
		self.title.setText(_translate("AddEmpInfoDialog", "员工信息"))
		self.male.setText(_translate("AddEmpInfoDialog", "男"))
		self.female.setText(_translate("AddEmpInfoDialog", "女"))
		self.label_department.setText(_translate("AddEmpInfoDialog", "部门："))
		self.label_home_address.setText(_translate("AddEmpInfoDialog", "家庭住址："))
		self.department.setItemText(0, _translate("AddEmpInfoDialog", "财务部"))
		self.department.setItemText(1, _translate("AddEmpInfoDialog", "人事部"))
		self.department.setItemText(2, _translate("AddEmpInfoDialog", "生产部"))
		self.department.setItemText(3, _translate("AddEmpInfoDialog", "营销部"))
		self.label_entry_time.setText(_translate("AddEmpInfoDialog", "入职时间："))
		self.label_position.setText(_translate("AddEmpInfoDialog", "职务："))
		self.position.setItemText(0, _translate("AddEmpInfoDialog", "总监"))
		self.position.setItemText(1, _translate("AddEmpInfoDialog", "主管"))
		self.position.setItemText(2, _translate("AddEmpInfoDialog", "经理"))
		self.position.setItemText(3, _translate("AddEmpInfoDialog", "后勤"))
		self.position.setItemText(4, _translate("AddEmpInfoDialog", "工人"))
		self.position.setItemText(5, _translate("AddEmpInfoDialog", "会计"))
		self.position.setItemText(6, _translate("AddEmpInfoDialog", "专员"))
		self.position.setItemText(7, _translate("AddEmpInfoDialog", "组长"))
		self.label_educational_background.setText(_translate("AddEmpInfoDialog", "学历："))
		self.educational_background.setItemText(0, _translate("AddEmpInfoDialog", "本科"))
		self.educational_background.setItemText(1, _translate("AddEmpInfoDialog", "专科"))
		self.educational_background.setItemText(2, _translate("AddEmpInfoDialog", "小学"))
		self.educational_background.setItemText(3, _translate("AddEmpInfoDialog", "初中"))
		self.educational_background.setItemText(4, _translate("AddEmpInfoDialog", "研究生"))
		self.educational_background.setItemText(5, _translate("AddEmpInfoDialog", "硕士生"))
		self.educational_background.setItemText(6, _translate("AddEmpInfoDialog", "博士"))
		self.educational_background.setItemText(7, _translate("AddEmpInfoDialog", "博士后"))
		self.label_sex.setText(_translate("AddEmpInfoDialog", "性别："))
		self.label_phone.setText(_translate("AddEmpInfoDialog", "电话："))
		self.label_age.setText(_translate("AddEmpInfoDialog", "年龄："))
		self.label_ID_card.setText(_translate("AddEmpInfoDialog", "身份证："))
		self.label_graduated_school.setText(_translate("AddEmpInfoDialog", "毕业学校："))
		self.label_name.setText(_translate("AddEmpInfoDialog", "姓名："))
		self.label_number.setText(_translate("AddEmpInfoDialog", "编号："))
		self.label_year.setText(_translate("AddEmpInfoDialog", "年"))
		self.label_month.setText(_translate("AddEmpInfoDialog", "月"))
		self.label_day.setText(_translate("AddEmpInfoDialog", "日"))
		self.label_year_old.setText(_translate("AddEmpInfoDialog", "岁"))
		self.label_personal_profile.setText(_translate("AddEmpInfoDialog", "个人简介："))
		self.add.setText(_translate("AddEmpInfoDialog", "添加"))
		self.cancel.setText(_translate("AddEmpInfoDialog", "取消"))


# 重写带点击事件的LineEdit控件，用于提示文本为空
class PromptLineEdit(QtWidgets.QLineEdit):
	def __init__(self, parent= None):
		super(PromptLineEdit, self).__init__(parent)

	def mousePressEvent(self, e):
		if self.styleSheet() == 'background-color: red':
			self.setPlaceholderText('')
			self.setAlignment(QtCore.Qt.AlignLeft)
			self.setStyleSheet('')

	def textFiltering(self):
		reg_num = QRegExp('^[0-9]{5}$')
		validator_num=QRegExpValidator(self)
		validator_num.setRegExp(reg_num)
		self.setValidator(validator_num)


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	Page = QtWidgets.QWidget()
	ui = Ui_Page()
	ui.setupUi(Page)
	Page.show()
	sys.exit(app.exec_())

