# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Eric6_Workspace\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from salary import Salary
from employee import Employee

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1300, 800)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/money-bag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		# 标志位，用于标识菜单展开或收缩状态
		self.is_expanded = False
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.widget = QtWidgets.QWidget(self.centralwidget)
		self.widget.setMinimumSize(QtCore.QSize(1300, 800))
		self.widget.setStyleSheet("QWidget#widget {\n"
"	border-image: url(:/mainwindow/images/mainwindow/background.png);\n"
"}\n"
"QGroupBox {\n"
"	background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"									  stop: 0 #E0E0E0, stop: 1 #c8c8c8);\n"
"	border: 2px solid gray;\n"
"	border-radius: 5px;\n"
"	margin-top: 1.5ex;\n"
"}\n"
"QGroupBox::title {\n"
"	subcontrol-origin: margin;\n"
"	left: 15px;\n"
"}\n"
"QPushButton {\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.161765 rgba(165, 216, 255, 255), stop:1 rgba(0, 157, 255, 255));\n"
"\n"
"	border-style:outset;\n"
" \n"
"	border-width:2px;\n"
"\n"
"	border-color:#0055ff;\n"
"\n"
"	border-radius:10px;\n"
"\n"
"	min-width:100px;\n"
"\n"
"	min-height:20px;\n"
"\n"
"	padding:4px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.161765 rgba(120, 197, 255, 255), stop:1 rgba(0, 149, 242, 255));\n"
"	\n"
"	border-style:inset;\n"
"\n"
"	padding-left:6px;\n"
"\n"
"	padding-top:6px;\n"
"}\n"
"QLineEdit {\n"
"	height: 20px;\n"
"	border: 2px solid gray;\n"
"	border-radius: 10px;\n"
"	padding: 0 8px;\n"
"	background: lightBlue;\n"
"	selection-background-color: darkgray;\n"
"}\n"
"QPlainTextEdit {\n"
"	border: 2px solid gray;\n"
"	border-radius: 10px;\n"
"	background-color: lightBlue;\n"
"}\n"
"QSpinBox {\n"
"	border: 2px solid gray;\n"
"	background-color: lightBlue;\n"
"}")
		self.widget.setObjectName("widget")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
		self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_3.setSpacing(0)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.widget_10 = QtWidgets.QWidget(self.widget)
		self.widget_10.setObjectName("widget_10")
		self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_10)
		self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_19.setSpacing(0)
		self.horizontalLayout_19.setObjectName("horizontalLayout_19")
		self.rolling_subtitles = ClickedLabel(self, self.widget_10)
		self.rolling_subtitles.setMinimumSize(QtCore.QSize(0, 30))
		self.rolling_subtitles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.rolling_subtitles.setStyleSheet("QLabel {\n"
"color: red;\n"
"}\n")
		self.rolling_subtitles.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.rolling_subtitles.setAlignment(QtCore.Qt.AlignCenter)
		self.rolling_subtitles.setObjectName("rolling_subtitles")
		self.horizontalLayout_19.addWidget(self.rolling_subtitles)
		self.current_account = ClickedLabel(self, self.widget_10)
		self.current_account.setMinimumSize(QtCore.QSize(0, 30))
		self.current_account.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.current_account.setStyleSheet("QLabel#current_account {\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 178, 253, 255), stop:1 rgba(94, 148, 255, 255));\n"
"	border-bottom-left-radius: 30px;\n"
"	border-top-right-radius: 30px;\n"
"}\n"
"\n"
"")
		self.current_account.setAlignment(QtCore.Qt.AlignCenter)
		self.current_account.setObjectName("current_account")
		self.horizontalLayout_19.addWidget(self.current_account)
		self.horizontalLayout_19.setStretch(0, 4)
		self.horizontalLayout_19.setStretch(1, 1)
		self.gridLayout_3.addWidget(self.widget_10, 1, 1, 1, 1)
		self.treeWidget = QtWidgets.QTreeWidget(self.widget)
		self.treeWidget.setStyleSheet("QWidget {\n"
"	background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(162, 215, 255, 150), stop:1 rgba(165, 216, 255, 130));\n"
"}\n"
"QWidget::item {\n"
"	margin: 5px\n"
"}\n"
"\n"
"\n"
"")
		self.treeWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.treeWidget.setObjectName("treeWidget")
		self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
		item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_0.setIcon(0, icon1)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/salary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon2)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/employee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon3)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/attendance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon4)
		item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/form.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_0.setIcon(0, icon5)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon6)
		item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_0.setIcon(0, icon7)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/new_message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon8)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/message_record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon9)
		item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
		icon10 = QtGui.QIcon()
		icon10.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/other.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_0.setIcon(0, icon10)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon11 = QtGui.QIcon()
		icon11.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/modify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon11)
		item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
		icon12 = QtGui.QIcon()
		icon12.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_0.setIcon(0, icon12)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon13 = QtGui.QIcon()
		icon13.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/change_password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon13)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon14 = QtGui.QIcon()
		icon14.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/authorization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon14)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon15 = QtGui.QIcon()
		icon15.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/operation_record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon15)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon16 = QtGui.QIcon()
		icon16.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon16)
		item_1 = QtWidgets.QTreeWidgetItem(item_0)
		icon17 = QtGui.QIcon()
		icon17.addPixmap(QtGui.QPixmap(":/treewidget/images/treewidget/exit_system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		item_1.setIcon(0, icon17)
		self.treeWidget.header().setVisible(False)
		self.gridLayout_3.addWidget(self.treeWidget, 2, 0, 1, 1)
		self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
		self.stackedWidget.setStyleSheet("QStackedWidget > QWidget {\n"
"	background-color: rgba(149, 200, 247, 80);\n"
"}\n"
"")
		self.stackedWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.stackedWidget.setObjectName("stackedWidget")
		self.page_0 = QtWidgets.QWidget()
		self.page_0.setObjectName("page_0")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_0)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.widget_13 = QtWidgets.QWidget(self.page_0)
		self.widget_13.setObjectName("widget_13")
		self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_13)
		self.gridLayout_11.setObjectName("gridLayout_11")
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_11.addItem(spacerItem, 0, 1, 1, 1)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_11.addItem(spacerItem1, 1, 0, 1, 1)
		spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_11.addItem(spacerItem2, 2, 1, 1, 1)
		spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_11.addItem(spacerItem3, 1, 2, 1, 1)
		self.label_6 = QtWidgets.QLabel(self.widget_13)
		font = QtGui.QFont()
		font.setFamily("幼圆")
		font.setPointSize(36)
		self.label_6.setFont(font)
		self.label_6.setObjectName("label_6")
		self.gridLayout_11.addWidget(self.label_6, 1, 1, 1, 1)
		self.verticalLayout_6.addWidget(self.widget_13)
		self.stackedWidget.addWidget(self.page_0)
		
		
		self.page_1 = QtWidgets.QWidget()
		self.page_1.setObjectName("page_1")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_1)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.salary = Salary(self.page_1)
		
		
		# 员工工资表初始页面
		# self.widget_3 = QtWidgets.QWidget(self.page_1)
		# self.widget_3.setObjectName("widget_3")
		# self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
		# self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
		# self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		# self.groupBox_2 = QtWidgets.QGroupBox(self.widget_3)
		# self.groupBox_2.setObjectName("groupBox_2")
		# self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
		# self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		# self.label_2 = QtWidgets.QLabel(self.groupBox_2)
		# self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		# self.label_2.setObjectName("label_2")
		# self.horizontalLayout_4.addWidget(self.label_2)
		# self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
		# self.comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
		# self.comboBox.setEditable(True)
		# self.comboBox.setMaxCount(12)
		# self.comboBox.setFrame(True)
		# self.comboBox.setObjectName("comboBox")
		# self.comboBox.addItem("")
		# self.comboBox.addItem("")
		# self.comboBox.addItem("")
		# self.comboBox.addItem("")
		# self.comboBox.addItem("")
		# self.horizontalLayout_4.addWidget(self.comboBox)
		# self.label_3 = QtWidgets.QLabel(self.groupBox_2)
		# self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		# self.label_3.setObjectName("label_3")
		# self.horizontalLayout_4.addWidget(self.label_3)
		# self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
		# self.pushButton_12.setObjectName("pushButton_12")
		# self.horizontalLayout_4.addWidget(self.pushButton_12)
		# self.horizontalLayout_2.addWidget(self.groupBox_2)
		# self.groupBox_5 = QtWidgets.QGroupBox(self.widget_3)
		# self.groupBox_5.setObjectName("groupBox_5")
		# self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
		# self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		# self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_5)
		# self.lineEdit_31.setFrame(True)
		# self.lineEdit_31.setClearButtonEnabled(True)
		# self.lineEdit_31.setObjectName("lineEdit_31")
		# self.horizontalLayout_6.addWidget(self.lineEdit_31)
		# self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
		# self.pushButton_10.setObjectName("pushButton_10")
		# self.horizontalLayout_6.addWidget(self.pushButton_10)
		# self.horizontalLayout_2.addWidget(self.groupBox_5)
		# self.horizontalLayout_2.setStretch(0, 2)
		# self.horizontalLayout_2.setStretch(1, 3)
		# self.verticalLayout_3.addWidget(self.widget_3)
		# self.groupBox_8 = QtWidgets.QGroupBox(self.page_1)
		# self.groupBox_8.setObjectName("groupBox_8")
		# self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
		# self.verticalLayout.setObjectName("verticalLayout")
		# self.label_53 = QtWidgets.QLabel(self.groupBox_8)
		# self.label_53.setStyleSheet("background-color: rgb(218, 218, 218);")
		# self.label_53.setAlignment(QtCore.Qt.AlignCenter)
		# self.label_53.setObjectName("label_53")
		# self.verticalLayout.addWidget(self.label_53)
		# self.tableView = QtWidgets.QTableView(self.groupBox_8)
		# self.tableView.setGridStyle(QtCore.Qt.DashDotLine)
		# self.tableView.setObjectName("tableView")
		# self.verticalLayout.addWidget(self.tableView)
		# self.widget_7 = QtWidgets.QWidget(self.groupBox_8)
		# self.widget_7.setObjectName("widget_7")
		# self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
		# self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
		# self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		# self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
		# self.pushButton_5.setObjectName("pushButton_5")
		# self.horizontalLayout_3.addWidget(self.pushButton_5)
		# self.pushButton_14 = QtWidgets.QPushButton(self.widget_7)
		# self.pushButton_14.setObjectName("pushButton_14")
		# self.horizontalLayout_3.addWidget(self.pushButton_14)
		# self.label = QtWidgets.QLabel(self.widget_7)
		# self.label.setAlignment(QtCore.Qt.AlignCenter)
		# self.label.setObjectName("label")
		# self.horizontalLayout_3.addWidget(self.label)
		# self.pushButton_15 = QtWidgets.QPushButton(self.widget_7)
		# self.pushButton_15.setObjectName("pushButton_15")
		# self.horizontalLayout_3.addWidget(self.pushButton_15)
		# self.pushButton_16 = QtWidgets.QPushButton(self.widget_7)
		# self.pushButton_16.setObjectName("pushButton_16")
		# self.horizontalLayout_3.addWidget(self.pushButton_16)
		# self.verticalLayout.addWidget(self.widget_7)
		# self.verticalLayout_3.addWidget(self.groupBox_8)
		
		self.stackedWidget.addWidget(self.page_1)
		
		# 员工信息表页面
		self.page_2 = QtWidgets.QWidget()
		self.page_2.setObjectName("page_2")
		self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.emp = Employee(self.page_2)
		
		# 员工信息表初始页面
		# self.groupBox_16 = QtWidgets.QGroupBox(self.page_2)
		# self.groupBox_16.setObjectName("groupBox_16")
		# self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_16)
		# self.verticalLayout_20.setObjectName("verticalLayout_20")
		# self.label_58 = QtWidgets.QLabel(self.groupBox_16)
		# self.label_58.setStyleSheet("background-color: rgb(218, 218, 218);")
		# self.label_58.setAlignment(QtCore.Qt.AlignCenter)
		# self.label_58.setObjectName("label_58")
		# self.verticalLayout_20.addWidget(self.label_58)
		# self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_16)
		# self.tableWidget_3.setFocusPolicy(QtCore.Qt.NoFocus)
		# self.tableWidget_3.setTabKeyNavigation(True)
		# self.tableWidget_3.setGridStyle(QtCore.Qt.DashDotLine)
		# self.tableWidget_3.setObjectName("tableWidget_3")
		# self.tableWidget_3.setColumnCount(14)
		# self.tableWidget_3.setRowCount(33)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(0, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(1, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(2, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(3, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(4, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(5, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(6, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(7, item)
		# item = QtWidgets.QTableWidgetItem()
		# item.setTextAlignment(QtCore.Qt.AlignCenter)
		# self.tableWidget_3.setVerticalHeaderItem(8, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(9, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(10, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(11, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(12, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(13, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(14, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(15, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(16, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(17, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(18, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(19, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(20, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(21, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(22, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(23, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(24, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(25, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(26, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(27, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(28, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(29, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(30, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(31, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setVerticalHeaderItem(32, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(0, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(1, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(2, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(3, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(4, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(5, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(6, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(7, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(8, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(9, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(10, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(11, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(12, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setHorizontalHeaderItem(13, item)
		# item = QtWidgets.QTableWidgetItem()
		# self.tableWidget_3.setItem(0, 0, item)
		# self.verticalLayout_20.addWidget(self.tableWidget_3)
		# self.gridLayout_5.addWidget(self.groupBox_16, 1, 0, 1, 3)
		# self.groupBox_15 = QtWidgets.QGroupBox(self.page_2)
		# self.groupBox_15.setObjectName("groupBox_15")
		# self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_15)
		# self.horizontalLayout_20.setObjectName("horizontalLayout_20")
		# self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_15)
		# self.lineEdit_38.setFrame(True)
		# self.lineEdit_38.setClearButtonEnabled(True)
		# self.lineEdit_38.setObjectName("lineEdit_38")
		# self.horizontalLayout_20.addWidget(self.lineEdit_38)
		# self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_15)
		# self.pushButton_26.setObjectName("pushButton_26")
		# self.horizontalLayout_20.addWidget(self.pushButton_26)
		# self.gridLayout_5.addWidget(self.groupBox_15, 0, 0, 1, 1)
		# self.groupBox_13 = QtWidgets.QGroupBox(self.page_2)
		# self.groupBox_13.setObjectName("groupBox_13")
		# self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_13)
		# self.horizontalLayout_15.setObjectName("horizontalLayout_15")
		# self.pushButton = QtWidgets.QPushButton(self.groupBox_13)
		# self.pushButton.setObjectName("pushButton")
		# self.horizontalLayout_15.addWidget(self.pushButton)
		# self.gridLayout_5.addWidget(self.groupBox_13, 0, 2, 1, 1)
		# self.groupBox_14 = QtWidgets.QGroupBox(self.page_2)
		# self.groupBox_14.setObjectName("groupBox_14")
		# self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_14)
		# self.horizontalLayout_16.setObjectName("horizontalLayout_16")
		# self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_14)
		# self.radioButton_3.setChecked(True)
		# self.radioButton_3.setObjectName("radioButton_3")
		# self.horizontalLayout_16.addWidget(self.radioButton_3)
		# self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_14)
		# self.radioButton_4.setObjectName("radioButton_4")
		# self.horizontalLayout_16.addWidget(self.radioButton_4)
		# self.gridLayout_5.addWidget(self.groupBox_14, 0, 1, 1, 1)
		# self.info_form_page_bar = QtWidgets.QWidget(self.page_2)
		# self.info_form_page_bar.setObjectName("info_form_page_bar")
		# self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.info_form_page_bar)
		# self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
		# self.horizontalLayout_21.setObjectName("horizontalLayout_21")
		# self.info_form_first_page = QtWidgets.QPushButton(self.info_form_page_bar)
		# self.info_form_first_page.setObjectName("info_form_first_page")
		# self.horizontalLayout_21.addWidget(self.info_form_first_page)
		# self.info_form_previous_page = QtWidgets.QPushButton(self.info_form_page_bar)
		# self.info_form_previous_page.setObjectName("info_form_previous_page")
		# self.horizontalLayout_21.addWidget(self.info_form_previous_page)
		# self.info_form_page_num = QtWidgets.QLabel(self.info_form_page_bar)
		# self.info_form_page_num.setAlignment(QtCore.Qt.AlignCenter)
		# self.info_form_page_num.setObjectName("info_form_page_num")
		# self.horizontalLayout_21.addWidget(self.info_form_page_num)
		# self.info_form_next_page = QtWidgets.QPushButton(self.info_form_page_bar)
		# self.info_form_next_page.setObjectName("info_form_next_page")
		# self.horizontalLayout_21.addWidget(self.info_form_next_page)
		# self.info_form_last_page = QtWidgets.QPushButton(self.info_form_page_bar)
		# self.info_form_last_page.setObjectName("info_form_last_page")
		# self.horizontalLayout_21.addWidget(self.info_form_last_page)
		# self.gridLayout_5.addWidget(self.info_form_page_bar, 2, 0, 1, 3)
		
		self.stackedWidget.addWidget(self.page_2)
		self.page_3 = QtWidgets.QWidget()
		self.page_3.setObjectName("page_3")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.widget_11 = QtWidgets.QWidget(self.page_3)
		self.widget_11.setObjectName("widget_11")
		self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_11)
		self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_11.setObjectName("horizontalLayout_11")
		self.groupBox_10 = QtWidgets.QGroupBox(self.widget_11)
		self.groupBox_10.setObjectName("groupBox_10")
		self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_10)
		self.horizontalLayout_12.setObjectName("horizontalLayout_12")
		self.label_13 = QtWidgets.QLabel(self.groupBox_10)
		self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_13.setObjectName("label_13")
		self.horizontalLayout_12.addWidget(self.label_13)
		self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_10)
		self.comboBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
		self.comboBox_3.setEditable(True)
		self.comboBox_3.setMaxCount(12)
		self.comboBox_3.setFrame(True)
		self.comboBox_3.setObjectName("comboBox_3")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.horizontalLayout_12.addWidget(self.comboBox_3)
		self.label_14 = QtWidgets.QLabel(self.groupBox_10)
		self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_14.setObjectName("label_14")
		self.horizontalLayout_12.addWidget(self.label_14)
		self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_10)
		self.pushButton_17.setObjectName("pushButton_17")
		self.horizontalLayout_12.addWidget(self.pushButton_17)
		self.horizontalLayout_11.addWidget(self.groupBox_10)
		self.groupBox_11 = QtWidgets.QGroupBox(self.widget_11)
		self.groupBox_11.setObjectName("groupBox_11")
		self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_11)
		self.horizontalLayout_13.setObjectName("horizontalLayout_13")
		self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_11)
		self.lineEdit_34.setFrame(True)
		self.lineEdit_34.setClearButtonEnabled(True)
		self.lineEdit_34.setObjectName("lineEdit_34")
		self.horizontalLayout_13.addWidget(self.lineEdit_34)
		self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_11)
		self.pushButton_18.setObjectName("pushButton_18")
		self.horizontalLayout_13.addWidget(self.pushButton_18)
		self.horizontalLayout_11.addWidget(self.groupBox_11)
		self.horizontalLayout_11.setStretch(0, 2)
		self.horizontalLayout_11.setStretch(1, 3)
		self.verticalLayout_7.addWidget(self.widget_11)
		self.groupBox_4 = QtWidgets.QGroupBox(self.page_3)
		self.groupBox_4.setObjectName("groupBox_4")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.label_51 = QtWidgets.QLabel(self.groupBox_4)
		self.label_51.setStyleSheet("background-color: rgb(218, 218, 218);")
		self.label_51.setAlignment(QtCore.Qt.AlignCenter)
		self.label_51.setObjectName("label_51")
		self.verticalLayout_4.addWidget(self.label_51)
		self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_4)
		self.tableWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
		self.tableWidget_2.setTabKeyNavigation(True)
		self.tableWidget_2.setGridStyle(QtCore.Qt.DashDotLine)
		self.tableWidget_2.setObjectName("tableWidget_2")
		self.tableWidget_2.setColumnCount(9)
		self.tableWidget_2.setRowCount(33)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_2.setVerticalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(9, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(10, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(11, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(12, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(13, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(14, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(15, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(16, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(17, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(18, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(19, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(20, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(21, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(22, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(23, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(24, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(25, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(26, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(27, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(28, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(29, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(30, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(31, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setVerticalHeaderItem(32, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setItem(0, 0, item)
		self.verticalLayout_4.addWidget(self.tableWidget_2)
		self.verticalLayout_7.addWidget(self.groupBox_4)
		self.widget_12 = QtWidgets.QWidget(self.page_3)
		self.widget_12.setObjectName("widget_12")
		self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_12)
		self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_14.setObjectName("horizontalLayout_14")
		self.pushButton_19 = QtWidgets.QPushButton(self.widget_12)
		self.pushButton_19.setObjectName("pushButton_19")
		self.horizontalLayout_14.addWidget(self.pushButton_19)
		self.pushButton_20 = QtWidgets.QPushButton(self.widget_12)
		self.pushButton_20.setObjectName("pushButton_20")
		self.horizontalLayout_14.addWidget(self.pushButton_20)
		self.label_15 = QtWidgets.QLabel(self.widget_12)
		self.label_15.setAlignment(QtCore.Qt.AlignCenter)
		self.label_15.setObjectName("label_15")
		self.horizontalLayout_14.addWidget(self.label_15)
		self.pushButton_21 = QtWidgets.QPushButton(self.widget_12)
		self.pushButton_21.setObjectName("pushButton_21")
		self.horizontalLayout_14.addWidget(self.pushButton_21)
		self.pushButton_22 = QtWidgets.QPushButton(self.widget_12)
		self.pushButton_22.setObjectName("pushButton_22")
		self.horizontalLayout_14.addWidget(self.pushButton_22)
		self.verticalLayout_7.addWidget(self.widget_12)
		self.stackedWidget.addWidget(self.page_3)
		self.page_4 = QtWidgets.QWidget()
		self.page_4.setObjectName("page_4")
		self.gridLayout_10 = QtWidgets.QGridLayout(self.page_4)
		self.gridLayout_10.setObjectName("gridLayout_10")
		self.groupBox_18 = QtWidgets.QGroupBox(self.page_4)
		self.groupBox_18.setObjectName("groupBox_18")
		self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_18)
		self.horizontalLayout_18.setObjectName("horizontalLayout_18")
		self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_18)
		self.pushButton_23.setObjectName("pushButton_23")
		self.horizontalLayout_18.addWidget(self.pushButton_23)
		self.gridLayout_10.addWidget(self.groupBox_18, 0, 3, 1, 1)
		self.groupBox_17 = QtWidgets.QGroupBox(self.page_4)
		self.groupBox_17.setObjectName("groupBox_17")
		self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_17)
		self.horizontalLayout_17.setObjectName("horizontalLayout_17")
		self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_17)
		self.comboBox_5.setObjectName("comboBox_5")
		self.comboBox_5.addItem("")
		self.comboBox_5.addItem("")
		self.comboBox_5.addItem("")
		self.horizontalLayout_17.addWidget(self.comboBox_5)
		self.gridLayout_10.addWidget(self.groupBox_17, 0, 0, 1, 1)
		self.groupBox_6 = QtWidgets.QGroupBox(self.page_4)
		self.groupBox_6.setObjectName("groupBox_6")
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_6)
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
		self.pushButton_6.setObjectName("pushButton_6")
		self.horizontalLayout_8.addWidget(self.pushButton_6)
		self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
		self.pushButton_7.setObjectName("pushButton_7")
		self.horizontalLayout_8.addWidget(self.pushButton_7)
		self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
		self.pushButton_13.setObjectName("pushButton_13")
		self.horizontalLayout_8.addWidget(self.pushButton_13)
		self.gridLayout_10.addWidget(self.groupBox_6, 0, 1, 1, 1)
		spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_10.addItem(spacerItem4, 0, 2, 1, 1)
		self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
		self.groupBox_7.setObjectName("groupBox_7")
		self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
		self.verticalLayout_9.setObjectName("verticalLayout_9")
		self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_7)
		self.tableWidget_4.setFocusPolicy(QtCore.Qt.NoFocus)
		self.tableWidget_4.setGridStyle(QtCore.Qt.DashDotLine)
		self.tableWidget_4.setObjectName("tableWidget_4")
		self.tableWidget_4.setColumnCount(5)
		self.tableWidget_4.setRowCount(34)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		self.tableWidget_4.setVerticalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(9, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(10, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(11, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(12, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(13, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(14, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(15, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(16, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(17, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(18, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(19, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(20, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(21, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(22, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(23, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(24, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(25, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(26, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(27, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(28, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(29, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(30, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(31, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(32, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setVerticalHeaderItem(33, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setItem(0, 0, item)
		self.verticalLayout_9.addWidget(self.tableWidget_4)
		self.gridLayout_10.addWidget(self.groupBox_7, 1, 0, 1, 4)
		self.stackedWidget.addWidget(self.page_4)
		self.page_5 = QtWidgets.QWidget()
		self.page_5.setObjectName("page_5")
		self.gridLayout_9 = QtWidgets.QGridLayout(self.page_5)
		self.gridLayout_9.setObjectName("gridLayout_9")
		spacerItem5 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_9.addItem(spacerItem5, 1, 1, 1, 1)
		spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_9.addItem(spacerItem6, 2, 0, 1, 1)
		self.pushButton_2 = QtWidgets.QPushButton(self.page_5)
		self.pushButton_2.setMinimumSize(QtCore.QSize(112, 32))
		self.pushButton_2.setObjectName("pushButton_2")
		self.gridLayout_9.addWidget(self.pushButton_2, 2, 1, 1, 1)
		spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_9.addItem(spacerItem7, 2, 2, 1, 1)
		spacerItem8 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_9.addItem(spacerItem8, 3, 1, 1, 1)
		self.groupBox_12 = QtWidgets.QGroupBox(self.page_5)
		self.groupBox_12.setObjectName("groupBox_12")
		self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_12)
		self.gridLayout_7.setObjectName("gridLayout_7")
		self.label_22 = QtWidgets.QLabel(self.groupBox_12)
		self.label_22.setObjectName("label_22")
		self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
		self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_12)
		self.plainTextEdit_3.setObjectName("plainTextEdit_3")
		self.gridLayout_7.addWidget(self.plainTextEdit_3, 0, 1, 1, 1)
		self.label_23 = QtWidgets.QLabel(self.groupBox_12)
		self.label_23.setObjectName("label_23")
		self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
		self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox_12)
		self.plainTextEdit_5.setObjectName("plainTextEdit_5")
		self.gridLayout_7.addWidget(self.plainTextEdit_5, 1, 1, 1, 1)
		self.gridLayout_9.addWidget(self.groupBox_12, 0, 0, 1, 3)
		self.stackedWidget.addWidget(self.page_5)
		self.page_6 = QtWidgets.QWidget()
		self.page_6.setObjectName("page_6")
		self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
		self.gridLayout_6.setObjectName("gridLayout_6")
		self.widget_8 = QtWidgets.QWidget(self.page_6)
		self.widget_8.setObjectName("widget_8")
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.label_16 = QtWidgets.QLabel(self.widget_8)
		self.label_16.setObjectName("label_16")
		self.horizontalLayout_7.addWidget(self.label_16)
		self.comboBox_4 = QtWidgets.QComboBox(self.widget_8)
		self.comboBox_4.setObjectName("comboBox_4")
		self.comboBox_4.addItem("")
		self.comboBox_4.addItem("")
		self.comboBox_4.addItem("")
		self.horizontalLayout_7.addWidget(self.comboBox_4)
		self.label_17 = QtWidgets.QLabel(self.widget_8)
		self.label_17.setObjectName("label_17")
		self.horizontalLayout_7.addWidget(self.label_17)
		self.comboBox_6 = QtWidgets.QComboBox(self.widget_8)
		self.comboBox_6.setObjectName("comboBox_6")
		self.comboBox_6.addItem("")
		self.comboBox_6.addItem("")
		self.comboBox_6.addItem("")
		self.horizontalLayout_7.addWidget(self.comboBox_6)
		self.gridLayout_6.addWidget(self.widget_8, 0, 1, 1, 1)
		spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_6.addItem(spacerItem9, 0, 0, 1, 1)
		self.tableWidget_5 = QtWidgets.QTableWidget(self.page_6)
		self.tableWidget_5.setShowGrid(True)
		self.tableWidget_5.setGridStyle(QtCore.Qt.SolidLine)
		self.tableWidget_5.setRowCount(3)
		self.tableWidget_5.setObjectName("tableWidget_5")
		self.tableWidget_5.setColumnCount(8)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(7, item)
		self.tableWidget_5.horizontalHeader().setStretchLastSection(False)
		self.tableWidget_5.verticalHeader().setVisible(False)
		self.tableWidget_5.verticalHeader().setStretchLastSection(False)
		self.gridLayout_6.addWidget(self.tableWidget_5, 1, 0, 1, 2)
		self.stackedWidget.addWidget(self.page_6)
		self.page_7 = QtWidgets.QWidget()
		self.page_7.setObjectName("page_7")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_7)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.groupBox_9 = QtWidgets.QGroupBox(self.page_7)
		self.groupBox_9.setObjectName("groupBox_9")
		self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_9)
		self.verticalLayout_12.setObjectName("verticalLayout_12")
		self.label_54 = QtWidgets.QLabel(self.groupBox_9)
		self.label_54.setStyleSheet("background-color: rgb(218, 218, 218);")
		self.label_54.setAlignment(QtCore.Qt.AlignCenter)
		self.label_54.setObjectName("label_54")
		self.verticalLayout_12.addWidget(self.label_54)
		self.tableWidget = QtWidgets.QTableWidget(self.groupBox_9)
		self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
		self.tableWidget.setRowCount(14)
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.setColumnCount(8)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setItem(2, 2, item)
		self.verticalLayout_12.addWidget(self.tableWidget)
		self.verticalLayout_8.addWidget(self.groupBox_9)
		self.stackedWidget.addWidget(self.page_7)
		self.page_8 = QtWidgets.QWidget()
		self.page_8.setObjectName("page_8")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.page_8)
		self.gridLayout_4.setObjectName("gridLayout_4")
		spacerItem10 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 1)
		self.groupBox = QtWidgets.QGroupBox(self.page_8)
		self.groupBox.setObjectName("groupBox")
		self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
		self.formLayout_2.setObjectName("formLayout_2")
		self.label_8 = QtWidgets.QLabel(self.groupBox)
		self.label_8.setObjectName("label_8")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
		self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
		self.label_12 = QtWidgets.QLabel(self.groupBox)
		self.label_12.setObjectName("label_12")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
		self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
		self.lineEdit_5.setObjectName("lineEdit_5")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
		self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
		self.lineEdit_6.setObjectName("lineEdit_6")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
		self.label_20 = QtWidgets.QLabel(self.groupBox)
		self.label_20.setObjectName("label_20")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
		self.gridLayout_4.addWidget(self.groupBox, 1, 1, 1, 1)
		spacerItem11 = QtWidgets.QSpacerItem(298, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_4.addItem(spacerItem11, 0, 1, 1, 1)
		spacerItem12 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_4.addItem(spacerItem12, 1, 2, 1, 1)
		spacerItem13 = QtWidgets.QSpacerItem(366, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_4.addItem(spacerItem13, 3, 1, 1, 1)
		self.widget_9 = QtWidgets.QWidget(self.page_8)
		self.widget_9.setObjectName("widget_9")
		self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_9)
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		spacerItem14 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem14)
		self.okButton = QtWidgets.QPushButton(self.widget_9)
		self.okButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.okButton.setAutoDefault(False)
		self.okButton.setObjectName("okButton")
		self.horizontalLayout_10.addWidget(self.okButton)
		spacerItem15 = QtWidgets.QSpacerItem(79, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem15)
		self.gridLayout_4.addWidget(self.widget_9, 2, 1, 1, 1)
		self.stackedWidget.addWidget(self.page_8)
		self.page_9 = QtWidgets.QWidget()
		self.page_9.setObjectName("page_9")
		self.gridLayout_8 = QtWidgets.QGridLayout(self.page_9)
		self.gridLayout_8.setObjectName("gridLayout_8")
		spacerItem16 = QtWidgets.QSpacerItem(20, 264, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_8.addItem(spacerItem16, 0, 1, 1, 1)
		spacerItem17 = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_8.addItem(spacerItem17, 1, 0, 1, 1)
		self.widget_15 = QtWidgets.QWidget(self.page_9)
		self.widget_15.setObjectName("widget_15")
		self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_15)
		self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_22.setSpacing(0)
		self.horizontalLayout_22.setObjectName("horizontalLayout_22")
		self.groupBox_19 = QtWidgets.QGroupBox(self.widget_15)
		self.groupBox_19.setObjectName("groupBox_19")
		self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox_19)
		self.horizontalLayout_23.setObjectName("horizontalLayout_23")
		self.label_25 = QtWidgets.QLabel(self.groupBox_19)
		self.label_25.setObjectName("label_25")
		self.horizontalLayout_23.addWidget(self.label_25)
		self.lineEdit = QtWidgets.QLineEdit(self.groupBox_19)
		self.lineEdit.setObjectName("lineEdit")
		self.horizontalLayout_23.addWidget(self.lineEdit)
		self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_19)
		self.pushButton_3.setObjectName("pushButton_3")
		self.horizontalLayout_23.addWidget(self.pushButton_3)
		self.line = QtWidgets.QFrame(self.groupBox_19)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_23.addWidget(self.line)
		self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_19)
		self.pushButton_4.setObjectName("pushButton_4")
		self.horizontalLayout_23.addWidget(self.pushButton_4)
		self.horizontalLayout_22.addWidget(self.groupBox_19)
		self.gridLayout_8.addWidget(self.widget_15, 1, 1, 1, 1)
		spacerItem18 = QtWidgets.QSpacerItem(253, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_8.addItem(spacerItem18, 1, 2, 1, 1)
		spacerItem19 = QtWidgets.QSpacerItem(20, 263, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_8.addItem(spacerItem19, 2, 1, 1, 1)
		self.stackedWidget.addWidget(self.page_9)
		self.page_10 = QtWidgets.QWidget()
		self.page_10.setObjectName("page_10")
		self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_10)
		self.verticalLayout_11.setObjectName("verticalLayout_11")
		self.widget_16 = QtWidgets.QWidget(self.page_10)
		self.widget_16.setObjectName("widget_16")
		self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_16)
		self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_13.setSpacing(0)
		self.verticalLayout_13.setObjectName("verticalLayout_13")
		self.groupBox_20 = QtWidgets.QGroupBox(self.widget_16)
		self.groupBox_20.setObjectName("groupBox_20")
		self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_20)
		self.verticalLayout_14.setObjectName("verticalLayout_14")
		self.tableWidget_6 = QtWidgets.QTableWidget(self.groupBox_20)
		self.tableWidget_6.setObjectName("tableWidget_6")
		self.tableWidget_6.setColumnCount(3)
		self.tableWidget_6.setRowCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(0, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(1, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setItem(1, 2, item)
		self.verticalLayout_14.addWidget(self.tableWidget_6)
		self.verticalLayout_13.addWidget(self.groupBox_20)
		self.verticalLayout_11.addWidget(self.widget_16)
		self.stackedWidget.addWidget(self.page_10)
		self.add_emp = QtWidgets.QWidget()
		self.add_emp.setObjectName("add_emp")
		self.gridLayout = QtWidgets.QGridLayout(self.add_emp)
		self.gridLayout.setObjectName("gridLayout")
		spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem20, 1, 0, 1, 1)
		spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem21, 3, 1, 1, 1)
		self.widget_14 = QtWidgets.QWidget(self.add_emp)
		self.widget_14.setObjectName("widget_14")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_14)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem22)
		self.pushButton_8 = QtWidgets.QPushButton(self.widget_14)
		self.pushButton_8.setObjectName("pushButton_8")
		self.horizontalLayout_5.addWidget(self.pushButton_8)
		spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem23)
		self.pushButton_9 = QtWidgets.QPushButton(self.widget_14)
		self.pushButton_9.setObjectName("pushButton_9")
		self.horizontalLayout_5.addWidget(self.pushButton_9)
		spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem24)
		self.gridLayout.addWidget(self.widget_14, 2, 1, 1, 1)
		self.groupBox_3 = QtWidgets.QGroupBox(self.add_emp)
		self.groupBox_3.setObjectName("groupBox_3")
		self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
		self.verticalLayout_10.setSpacing(21)
		self.verticalLayout_10.setObjectName("verticalLayout_10")
		self.label_38 = QtWidgets.QLabel(self.groupBox_3)
		self.label_38.setStyleSheet("background-color: rgb(200, 200, 200);")
		self.label_38.setAlignment(QtCore.Qt.AlignCenter)
		self.label_38.setObjectName("label_38")
		self.verticalLayout_10.addWidget(self.label_38)
		self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
		self.widget_4.setObjectName("widget_4")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setHorizontalSpacing(21)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.widget_2 = QtWidgets.QWidget(self.widget_4)
		self.widget_2.setObjectName("widget_2")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.radioButton = QtWidgets.QRadioButton(self.widget_2)
		self.radioButton.setObjectName("radioButton")
		self.horizontalLayout.addWidget(self.radioButton)
		self.radioButton_2 = QtWidgets.QRadioButton(self.widget_2)
		self.radioButton_2.setCheckable(True)
		self.radioButton_2.setChecked(True)
		self.radioButton_2.setObjectName("radioButton_2")
		self.horizontalLayout.addWidget(self.radioButton_2)
		self.gridLayout_2.addWidget(self.widget_2, 1, 1, 1, 1)
		self.label_45 = QtWidgets.QLabel(self.widget_4)
		self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_45.setObjectName("label_45")
		self.gridLayout_2.addWidget(self.label_45, 3, 0, 1, 1)
		self.label_68 = QtWidgets.QLabel(self.widget_4)
		self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_68.setObjectName("label_68")
		self.gridLayout_2.addWidget(self.label_68, 8, 0, 1, 1)
		self.comboBox_8 = QtWidgets.QComboBox(self.widget_4)
		self.comboBox_8.setMinimumSize(QtCore.QSize(170, 0))
		self.comboBox_8.setMaximumSize(QtCore.QSize(170, 16777215))
		self.comboBox_8.setObjectName("comboBox_8")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.comboBox_8.addItem("")
		self.gridLayout_2.addWidget(self.comboBox_8, 3, 1, 1, 1)
		self.label_7 = QtWidgets.QLabel(self.widget_4)
		self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_7.setObjectName("label_7")
		self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
		self.label_64 = QtWidgets.QLabel(self.widget_4)
		self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_64.setObjectName("label_64")
		self.gridLayout_2.addWidget(self.label_64, 3, 2, 1, 1)
		self.lineEdit_40 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_40.setObjectName("lineEdit_40")
		self.gridLayout_2.addWidget(self.lineEdit_40, 8, 1, 1, 4)
		self.comboBox_10 = QtWidgets.QComboBox(self.widget_4)
		self.comboBox_10.setMinimumSize(QtCore.QSize(170, 0))
		self.comboBox_10.setMaximumSize(QtCore.QSize(170, 16777215))
		self.comboBox_10.setObjectName("comboBox_10")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.comboBox_10.addItem("")
		self.gridLayout_2.addWidget(self.comboBox_10, 3, 3, 1, 1)
		self.lineEdit_25 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_25.setMinimumSize(QtCore.QSize(170, 0))
		self.lineEdit_25.setMaximumSize(QtCore.QSize(170, 16777215))
		self.lineEdit_25.setObjectName("lineEdit_25")
		self.gridLayout_2.addWidget(self.lineEdit_25, 5, 1, 1, 1)
		self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_24.setMinimumSize(QtCore.QSize(170, 0))
		self.lineEdit_24.setMaximumSize(QtCore.QSize(170, 16777215))
		self.lineEdit_24.setObjectName("lineEdit_24")
		self.gridLayout_2.addWidget(self.lineEdit_24, 1, 3, 1, 1)
		self.label_5 = QtWidgets.QLabel(self.widget_4)
		self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.label_5.setStyleSheet("border: 1px solid gray;\n"
"padding: 3px\n"
"")
		self.label_5.setPixmap(QtGui.QPixmap(":/form/images/default_avatar.png"))
		self.label_5.setScaledContents(True)
		self.label_5.setObjectName("label_5")
		self.gridLayout_2.addWidget(self.label_5, 0, 4, 4, 1)
		self.label_63 = QtWidgets.QLabel(self.widget_4)
		self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_63.setObjectName("label_63")
		self.gridLayout_2.addWidget(self.label_63, 2, 2, 1, 1)
		self.comboBox_2 = QtWidgets.QComboBox(self.widget_4)
		self.comboBox_2.setMinimumSize(QtCore.QSize(170, 0))
		self.comboBox_2.setMaximumSize(QtCore.QSize(170, 16777215))
		self.comboBox_2.setObjectName("comboBox_2")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.gridLayout_2.addWidget(self.comboBox_2, 2, 3, 1, 1)
		self.label_4 = QtWidgets.QLabel(self.widget_4)
		self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_4.setObjectName("label_4")
		self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
		self.label_48 = QtWidgets.QLabel(self.widget_4)
		self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_48.setObjectName("label_48")
		self.gridLayout_2.addWidget(self.label_48, 2, 0, 1, 1)
		self.label_44 = QtWidgets.QLabel(self.widget_4)
		self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_44.setObjectName("label_44")
		self.gridLayout_2.addWidget(self.label_44, 1, 2, 1, 1)
		self.lineEdit_35 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_35.setMinimumSize(QtCore.QSize(170, 0))
		self.lineEdit_35.setMaximumSize(QtCore.QSize(170, 16777215))
		self.lineEdit_35.setObjectName("lineEdit_35")
		self.gridLayout_2.addWidget(self.lineEdit_35, 2, 1, 1, 1)
		self.label_62 = QtWidgets.QLabel(self.widget_4)
		self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_62.setObjectName("label_62")
		self.gridLayout_2.addWidget(self.label_62, 5, 0, 1, 1)
		self.lineEdit_33 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_33.setObjectName("lineEdit_33")
		self.gridLayout_2.addWidget(self.lineEdit_33, 7, 1, 1, 4)
		self.label_69 = QtWidgets.QLabel(self.widget_4)
		self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_69.setObjectName("label_69")
		self.gridLayout_2.addWidget(self.label_69, 7, 0, 1, 1)
		self.lineEdit_18 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_18.setMinimumSize(QtCore.QSize(170, 0))
		self.lineEdit_18.setMaximumSize(QtCore.QSize(170, 16777215))
		self.lineEdit_18.setObjectName("lineEdit_18")
		self.gridLayout_2.addWidget(self.lineEdit_18, 0, 3, 1, 1)
		self.label_41 = QtWidgets.QLabel(self.widget_4)
		self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_41.setObjectName("label_41")
		self.gridLayout_2.addWidget(self.label_41, 0, 2, 1, 1)
		self.label_55 = QtWidgets.QLabel(self.widget_4)
		self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_55.setObjectName("label_55")
		self.gridLayout_2.addWidget(self.label_55, 0, 0, 1, 1)
		self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_4)
		self.lineEdit_7.setMinimumSize(QtCore.QSize(170, 0))
		self.lineEdit_7.setMaximumSize(QtCore.QSize(170, 16777215))
		self.lineEdit_7.setObjectName("lineEdit_7")
		self.gridLayout_2.addWidget(self.lineEdit_7, 0, 1, 1, 1)
		self.widget_5 = QtWidgets.QWidget(self.widget_4)
		self.widget_5.setObjectName("widget_5")
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
		self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.spinBox = QtWidgets.QSpinBox(self.widget_5)
		self.spinBox.setMinimum(2017)
		self.spinBox.setMaximum(2050)
		self.spinBox.setObjectName("spinBox")
		self.horizontalLayout_9.addWidget(self.spinBox)
		self.label_9 = QtWidgets.QLabel(self.widget_5)
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.horizontalLayout_9.addWidget(self.label_9)
		self.spinBox_2 = QtWidgets.QSpinBox(self.widget_5)
		self.spinBox_2.setMinimum(1)
		self.spinBox_2.setMaximum(12)
		self.spinBox_2.setObjectName("spinBox_2")
		self.horizontalLayout_9.addWidget(self.spinBox_2)
		self.label_10 = QtWidgets.QLabel(self.widget_5)
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setObjectName("label_10")
		self.horizontalLayout_9.addWidget(self.label_10)
		self.spinBox_3 = QtWidgets.QSpinBox(self.widget_5)
		self.spinBox_3.setMinimum(1)
		self.spinBox_3.setMaximum(31)
		self.spinBox_3.setObjectName("spinBox_3")
		self.horizontalLayout_9.addWidget(self.spinBox_3)
		self.label_11 = QtWidgets.QLabel(self.widget_5)
		self.label_11.setAlignment(QtCore.Qt.AlignCenter)
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_9.addWidget(self.label_11)
		self.gridLayout_2.addWidget(self.widget_5, 6, 1, 1, 2)
		self.verticalLayout_10.addWidget(self.widget_4)
		self.widget_6 = QtWidgets.QWidget(self.groupBox_3)
		self.widget_6.setObjectName("widget_6")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
		self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.label_37 = QtWidgets.QLabel(self.widget_6)
		self.label_37.setObjectName("label_37")
		self.verticalLayout_5.addWidget(self.label_37)
		self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.widget_6)
		self.plainTextEdit_4.setMaximumSize(QtCore.QSize(16777215, 100))
		self.plainTextEdit_4.setFrameShadow(QtWidgets.QFrame.Plain)
		self.plainTextEdit_4.setObjectName("plainTextEdit_4")
		self.verticalLayout_5.addWidget(self.plainTextEdit_4)
		self.verticalLayout_10.addWidget(self.widget_6)
		self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
		spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem25, 1, 2, 1, 1)
		spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem26, 0, 1, 1, 1)
		self.stackedWidget.addWidget(self.add_emp)
		self.gridLayout_3.addWidget(self.stackedWidget, 2, 1, 1, 1)
		self.title = QtWidgets.QLabel(self.widget)
		self.title.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.title.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.title.setObjectName("title")
		self.gridLayout_3.addWidget(self.title, 0, 0, 1, 2)
		self.function_menu = ClickedLabel(self, self.widget)
		self.function_menu.setMinimumSize(QtCore.QSize(0, 30))
		self.function_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.function_menu.setStyleSheet("QLabel#function_menu {\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 157, 255, 150), stop:1 rgba(165, 216, 255, 150));\n"
"	border-top-left-radius: 30px;\n"
"	border-top-right-radius: 30px;\n"
"}\n"
"")
		self.function_menu.setAlignment(QtCore.Qt.AlignCenter)
		self.function_menu.setObjectName("function_menu")
		self.gridLayout_3.addWidget(self.function_menu, 1, 0, 1, 1)
		self.gridLayout_3.setColumnStretch(0, 1)
		self.gridLayout_3.setColumnStretch(1, 4)
		self.gridLayout_3.setRowStretch(0, 4)
		self.gridLayout_3.setRowStretch(1, 1)
		self.gridLayout_3.setRowStretch(2, 20)
		self.stackedWidget.raise_()
		self.widget_10.raise_()
		self.treeWidget.raise_()
		self.title.raise_()
		self.function_menu.raise_()
		self.verticalLayout_2.addWidget(self.widget)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		self.stackedWidget.setCurrentIndex(0)
		# self.comboBox.setCurrentIndex(4)
		self.comboBox_3.setCurrentIndex(4)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "工资管理系统"))
		self.rolling_subtitles.setToolTip(_translate("MainWindow", "点击回复消息"))
		self.rolling_subtitles.setText(_translate("MainWindow", "您有一条新消息！"))
		self.current_account.setToolTip(_translate("MainWindow", "点击切换账户"))
		self.current_account.setText(_translate("MainWindow", "当前账户：财务管理员"))
		__sortingEnabled = self.treeWidget.isSortingEnabled()
		self.treeWidget.setSortingEnabled(False)
		self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "管理"))
		self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "工资"))
		self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "员工"))
		self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "考勤"))
		self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "表"))
		self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Excel表"))
		self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "留言"))
		self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "新消息"))
		self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "消息记录"))
		self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "其他"))
		self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "工资调整记录"))
		self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "系统"))
		self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "修改密码"))
		self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "员工授权"))
		self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "操作记录"))
		self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "注销账号"))
		self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "退出系统"))
		self.treeWidget.setSortingEnabled(__sortingEnabled)
		self.label_6.setText(_translate("MainWindow", "欢迎您！XXX"))
		
		# 员工工资表
		# self.groupBox_2.setTitle(_translate("MainWindow", "按月份查询"))
		# self.label_2.setText(_translate("MainWindow", "2019年"))
		# self.comboBox.setItemText(0, _translate("MainWindow", "2"))
		# self.comboBox.setItemText(1, _translate("MainWindow", "3"))
		# self.comboBox.setItemText(2, _translate("MainWindow", "4"))
		# self.comboBox.setItemText(3, _translate("MainWindow", "11"))
		# self.comboBox.setItemText(4, _translate("MainWindow", "12"))
		# self.label_3.setText(_translate("MainWindow", "月"))
		# self.pushButton_12.setText(_translate("MainWindow", "查询"))
		# self.groupBox_5.setTitle(_translate("MainWindow", "按关键词搜索"))
		# self.lineEdit_31.setPlaceholderText(_translate("MainWindow", "模糊查询"))
		# self.pushButton_10.setText(_translate("MainWindow", "查询"))
		# self.groupBox_8.setTitle(_translate("MainWindow", "XXX公司"))
		# self.label_53.setText(_translate("MainWindow", "员工工资表"))
		# self.pushButton_5.setText(_translate("MainWindow", "首页"))
		# self.pushButton_14.setText(_translate("MainWindow", "上一页"))
		# self.label.setText(_translate("MainWindow", "[3/200]页"))
		# self.pushButton_15.setText(_translate("MainWindow", "下一页"))
		# self.pushButton_16.setText(_translate("MainWindow", "尾页"))
		
		# 员工信息表初始页面
		# self.groupBox_16.setTitle(_translate("MainWindow", "XXX公司"))
		# self.label_58.setText(_translate("MainWindow", "员工信息表"))
		# item = self.tableWidget_3.verticalHeaderItem(0)
		# item.setText(_translate("MainWindow", "1"))
		# item = self.tableWidget_3.verticalHeaderItem(1)
		# item.setText(_translate("MainWindow", "2"))
		# item = self.tableWidget_3.verticalHeaderItem(2)
		# item.setText(_translate("MainWindow", "3"))
		# item = self.tableWidget_3.verticalHeaderItem(3)
		# item.setText(_translate("MainWindow", "4"))
		# item = self.tableWidget_3.verticalHeaderItem(4)
		# item.setText(_translate("MainWindow", "5"))
		# item = self.tableWidget_3.verticalHeaderItem(5)
		# item.setText(_translate("MainWindow", "6"))
		# item = self.tableWidget_3.verticalHeaderItem(6)
		# item.setText(_translate("MainWindow", "7"))
		# item = self.tableWidget_3.verticalHeaderItem(7)
		# item.setText(_translate("MainWindow", "8"))
		# item = self.tableWidget_3.verticalHeaderItem(8)
		# item.setText(_translate("MainWindow", "9"))
		# item = self.tableWidget_3.verticalHeaderItem(9)
		# item.setText(_translate("MainWindow", "10"))
		# item = self.tableWidget_3.verticalHeaderItem(10)
		# item.setText(_translate("MainWindow", "11"))
		# item = self.tableWidget_3.verticalHeaderItem(11)
		# item.setText(_translate("MainWindow", "12"))
		# item = self.tableWidget_3.verticalHeaderItem(12)
		# item.setText(_translate("MainWindow", "13"))
		# item = self.tableWidget_3.verticalHeaderItem(13)
		# item.setText(_translate("MainWindow", "14"))
		# item = self.tableWidget_3.verticalHeaderItem(14)
		# item.setText(_translate("MainWindow", "15"))
		# item = self.tableWidget_3.verticalHeaderItem(15)
		# item.setText(_translate("MainWindow", "16"))
		# item = self.tableWidget_3.verticalHeaderItem(16)
		# item.setText(_translate("MainWindow", "17"))
		# item = self.tableWidget_3.verticalHeaderItem(17)
		# item.setText(_translate("MainWindow", "18"))
		# item = self.tableWidget_3.verticalHeaderItem(18)
		# item.setText(_translate("MainWindow", "19"))
		# item = self.tableWidget_3.verticalHeaderItem(19)
		# item.setText(_translate("MainWindow", "20"))
		# item = self.tableWidget_3.verticalHeaderItem(20)
		# item.setText(_translate("MainWindow", "21"))
		# item = self.tableWidget_3.verticalHeaderItem(21)
		# item.setText(_translate("MainWindow", "22"))
		# item = self.tableWidget_3.verticalHeaderItem(22)
		# item.setText(_translate("MainWindow", "24"))
		# item = self.tableWidget_3.verticalHeaderItem(23)
		# item.setText(_translate("MainWindow", "23"))
		# item = self.tableWidget_3.verticalHeaderItem(24)
		# item.setText(_translate("MainWindow", "25"))
		# item = self.tableWidget_3.verticalHeaderItem(25)
		# item.setText(_translate("MainWindow", "26"))
		# item = self.tableWidget_3.verticalHeaderItem(26)
		# item.setText(_translate("MainWindow", "28"))
		# item = self.tableWidget_3.verticalHeaderItem(27)
		# item.setText(_translate("MainWindow", "29"))
		# item = self.tableWidget_3.verticalHeaderItem(28)
		# item.setText(_translate("MainWindow", "30"))
		# item = self.tableWidget_3.verticalHeaderItem(29)
		# item.setText(_translate("MainWindow", "31"))
		# item = self.tableWidget_3.verticalHeaderItem(30)
		# item.setText(_translate("MainWindow", "32"))
		# item = self.tableWidget_3.verticalHeaderItem(31)
		# item.setText(_translate("MainWindow", "33"))
		# item = self.tableWidget_3.verticalHeaderItem(32)
		# item.setText(_translate("MainWindow", "35"))
		# item = self.tableWidget_3.horizontalHeaderItem(0)
		# item.setText(_translate("MainWindow", "编号"))
		# item = self.tableWidget_3.horizontalHeaderItem(1)
		# item.setText(_translate("MainWindow", "姓名"))
		# item = self.tableWidget_3.horizontalHeaderItem(2)
		# item.setText(_translate("MainWindow", "性别"))
		# item = self.tableWidget_3.horizontalHeaderItem(3)
		# item.setText(_translate("MainWindow", "部门"))
		# item = self.tableWidget_3.horizontalHeaderItem(4)
		# item.setText(_translate("MainWindow", "密码"))
		# item = self.tableWidget_3.horizontalHeaderItem(5)
		# item.setText(_translate("MainWindow", "电话"))
		# item = self.tableWidget_3.horizontalHeaderItem(6)
		# item.setText(_translate("MainWindow", "学历"))
		# item = self.tableWidget_3.horizontalHeaderItem(7)
		# item.setText(_translate("MainWindow", "职务"))
		# item = self.tableWidget_3.horizontalHeaderItem(8)
		# item.setText(_translate("MainWindow", "照片"))
		# item = self.tableWidget_3.horizontalHeaderItem(9)
		# item.setText(_translate("MainWindow", "身份证"))
		# item = self.tableWidget_3.horizontalHeaderItem(10)
		# item.setText(_translate("MainWindow", "入职时间"))
		# item = self.tableWidget_3.horizontalHeaderItem(11)
		# item.setText(_translate("MainWindow", "毕业学校"))
		# item = self.tableWidget_3.horizontalHeaderItem(12)
		# item.setText(_translate("MainWindow", "家庭住址"))
		# item = self.tableWidget_3.horizontalHeaderItem(13)
		# item.setText(_translate("MainWindow", "个人简介"))
		# __sortingEnabled = self.tableWidget_3.isSortingEnabled()
		# self.tableWidget_3.setSortingEnabled(False)
		# self.tableWidget_3.setSortingEnabled(__sortingEnabled)
		# self.groupBox_15.setTitle(_translate("MainWindow", "表格搜索"))
		# self.lineEdit_38.setPlaceholderText(_translate("MainWindow", "关键词查找"))
		# self.pushButton_26.setText(_translate("MainWindow", "查询"))
		# self.groupBox_13.setTitle(_translate("MainWindow", "表格操作"))
		# self.pushButton.setText(_translate("MainWindow", "提交"))
		# self.groupBox_14.setTitle(_translate("MainWindow", "表格状态"))
		# self.radioButton_3.setText(_translate("MainWindow", "不可编辑"))
		# self.radioButton_4.setText(_translate("MainWindow", "可编辑"))
		# self.info_form_first_page.setText(_translate("MainWindow", "首页"))
		# self.info_form_previous_page.setText(_translate("MainWindow", "上一页"))
		# self.info_form_page_num.setText(_translate("MainWindow", "[50/200]页"))
		# self.info_form_next_page.setText(_translate("MainWindow", "下一页"))
		# self.info_form_last_page.setText(_translate("MainWindow", "尾页"))
		
		self.groupBox_10.setTitle(_translate("MainWindow", "按月份查询"))
		self.label_13.setText(_translate("MainWindow", "2019年"))
		self.comboBox_3.setItemText(0, _translate("MainWindow", "2"))
		self.comboBox_3.setItemText(1, _translate("MainWindow", "3"))
		self.comboBox_3.setItemText(2, _translate("MainWindow", "4"))
		self.comboBox_3.setItemText(3, _translate("MainWindow", "11"))
		self.comboBox_3.setItemText(4, _translate("MainWindow", "12"))
		self.label_14.setText(_translate("MainWindow", "月"))
		self.pushButton_17.setText(_translate("MainWindow", "查询"))
		self.groupBox_11.setTitle(_translate("MainWindow", "按关键词搜索"))
		self.lineEdit_34.setPlaceholderText(_translate("MainWindow", "模糊查询"))
		self.pushButton_18.setText(_translate("MainWindow", "查询"))
		self.groupBox_4.setTitle(_translate("MainWindow", "XXX公司"))
		self.label_51.setText(_translate("MainWindow", "员工考勤表"))
		item = self.tableWidget_2.verticalHeaderItem(0)
		item.setText(_translate("MainWindow", "1"))
		item = self.tableWidget_2.verticalHeaderItem(1)
		item.setText(_translate("MainWindow", "2"))
		item = self.tableWidget_2.verticalHeaderItem(2)
		item.setText(_translate("MainWindow", "3"))
		item = self.tableWidget_2.verticalHeaderItem(3)
		item.setText(_translate("MainWindow", "4"))
		item = self.tableWidget_2.verticalHeaderItem(4)
		item.setText(_translate("MainWindow", "5"))
		item = self.tableWidget_2.verticalHeaderItem(5)
		item.setText(_translate("MainWindow", "6"))
		item = self.tableWidget_2.verticalHeaderItem(6)
		item.setText(_translate("MainWindow", "7"))
		item = self.tableWidget_2.verticalHeaderItem(7)
		item.setText(_translate("MainWindow", "8"))
		item = self.tableWidget_2.verticalHeaderItem(8)
		item.setText(_translate("MainWindow", "9"))
		item = self.tableWidget_2.verticalHeaderItem(9)
		item.setText(_translate("MainWindow", "10"))
		item = self.tableWidget_2.verticalHeaderItem(10)
		item.setText(_translate("MainWindow", "11"))
		item = self.tableWidget_2.verticalHeaderItem(11)
		item.setText(_translate("MainWindow", "12"))
		item = self.tableWidget_2.verticalHeaderItem(12)
		item.setText(_translate("MainWindow", "13"))
		item = self.tableWidget_2.verticalHeaderItem(13)
		item.setText(_translate("MainWindow", "14"))
		item = self.tableWidget_2.verticalHeaderItem(14)
		item.setText(_translate("MainWindow", "15"))
		item = self.tableWidget_2.verticalHeaderItem(15)
		item.setText(_translate("MainWindow", "16"))
		item = self.tableWidget_2.verticalHeaderItem(16)
		item.setText(_translate("MainWindow", "17"))
		item = self.tableWidget_2.verticalHeaderItem(17)
		item.setText(_translate("MainWindow", "18"))
		item = self.tableWidget_2.verticalHeaderItem(18)
		item.setText(_translate("MainWindow", "19"))
		item = self.tableWidget_2.verticalHeaderItem(19)
		item.setText(_translate("MainWindow", "20"))
		item = self.tableWidget_2.verticalHeaderItem(20)
		item.setText(_translate("MainWindow", "21"))
		item = self.tableWidget_2.verticalHeaderItem(21)
		item.setText(_translate("MainWindow", "22"))
		item = self.tableWidget_2.verticalHeaderItem(22)
		item.setText(_translate("MainWindow", "24"))
		item = self.tableWidget_2.verticalHeaderItem(23)
		item.setText(_translate("MainWindow", "23"))
		item = self.tableWidget_2.verticalHeaderItem(24)
		item.setText(_translate("MainWindow", "25"))
		item = self.tableWidget_2.verticalHeaderItem(25)
		item.setText(_translate("MainWindow", "26"))
		item = self.tableWidget_2.verticalHeaderItem(26)
		item.setText(_translate("MainWindow", "28"))
		item = self.tableWidget_2.verticalHeaderItem(27)
		item.setText(_translate("MainWindow", "29"))
		item = self.tableWidget_2.verticalHeaderItem(28)
		item.setText(_translate("MainWindow", "30"))
		item = self.tableWidget_2.verticalHeaderItem(29)
		item.setText(_translate("MainWindow", "31"))
		item = self.tableWidget_2.verticalHeaderItem(30)
		item.setText(_translate("MainWindow", "32"))
		item = self.tableWidget_2.verticalHeaderItem(31)
		item.setText(_translate("MainWindow", "33"))
		item = self.tableWidget_2.verticalHeaderItem(32)
		item.setText(_translate("MainWindow", "35"))
		item = self.tableWidget_2.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "编号"))
		item = self.tableWidget_2.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "姓名"))
		item = self.tableWidget_2.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "部门"))
		item = self.tableWidget_2.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "日期"))
		item = self.tableWidget_2.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "迟到"))
		item = self.tableWidget_2.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "早退"))
		item = self.tableWidget_2.horizontalHeaderItem(6)
		item.setText(_translate("MainWindow", "病假"))
		item = self.tableWidget_2.horizontalHeaderItem(7)
		item.setText(_translate("MainWindow", "事假"))
		item = self.tableWidget_2.horizontalHeaderItem(8)
		item.setText(_translate("MainWindow", "旷工"))
		__sortingEnabled = self.tableWidget_2.isSortingEnabled()
		self.tableWidget_2.setSortingEnabled(False)
		item = self.tableWidget_2.item(0, 0)
		item.setText(_translate("MainWindow", "不可编辑"))
		self.tableWidget_2.setSortingEnabled(__sortingEnabled)
		self.pushButton_19.setText(_translate("MainWindow", "首页"))
		self.pushButton_20.setText(_translate("MainWindow", "上一页"))
		self.label_15.setText(_translate("MainWindow", "[50/200]页"))
		self.pushButton_21.setText(_translate("MainWindow", "下一页"))
		self.pushButton_22.setText(_translate("MainWindow", "尾页"))
		self.groupBox_18.setTitle(_translate("MainWindow", "表格操作"))
		self.pushButton_23.setText(_translate("MainWindow", "提交"))
		self.groupBox_17.setTitle(_translate("MainWindow", "选择表"))
		self.comboBox_5.setItemText(0, _translate("MainWindow", "员工表"))
		self.comboBox_5.setItemText(1, _translate("MainWindow", "考勤表"))
		self.comboBox_5.setItemText(2, _translate("MainWindow", "工资表"))
		self.groupBox_6.setTitle(_translate("MainWindow", "Excel相关操作"))
		self.pushButton_6.setText(_translate("MainWindow", "导入Excel表"))
		self.pushButton_7.setText(_translate("MainWindow", "导出Excel表"))
		self.pushButton_13.setText(_translate("MainWindow", "打印"))
		self.groupBox_7.setTitle(_translate("MainWindow", "视图"))
		item = self.tableWidget_4.verticalHeaderItem(0)
		item.setText(_translate("MainWindow", "1"))
		item = self.tableWidget_4.verticalHeaderItem(1)
		item.setText(_translate("MainWindow", "2"))
		item = self.tableWidget_4.verticalHeaderItem(2)
		item.setText(_translate("MainWindow", "3"))
		item = self.tableWidget_4.verticalHeaderItem(3)
		item.setText(_translate("MainWindow", "4"))
		item = self.tableWidget_4.verticalHeaderItem(4)
		item.setText(_translate("MainWindow", "5"))
		item = self.tableWidget_4.verticalHeaderItem(5)
		item.setText(_translate("MainWindow", "6"))
		item = self.tableWidget_4.verticalHeaderItem(6)
		item.setText(_translate("MainWindow", "7"))
		item = self.tableWidget_4.verticalHeaderItem(7)
		item.setText(_translate("MainWindow", "8"))
		item = self.tableWidget_4.verticalHeaderItem(8)
		item.setText(_translate("MainWindow", "9"))
		item = self.tableWidget_4.verticalHeaderItem(9)
		item.setText(_translate("MainWindow", "10"))
		item = self.tableWidget_4.verticalHeaderItem(10)
		item.setText(_translate("MainWindow", "11"))
		item = self.tableWidget_4.verticalHeaderItem(11)
		item.setText(_translate("MainWindow", "12"))
		item = self.tableWidget_4.verticalHeaderItem(12)
		item.setText(_translate("MainWindow", "13"))
		item = self.tableWidget_4.verticalHeaderItem(13)
		item.setText(_translate("MainWindow", "14"))
		item = self.tableWidget_4.verticalHeaderItem(14)
		item.setText(_translate("MainWindow", "15"))
		item = self.tableWidget_4.verticalHeaderItem(15)
		item.setText(_translate("MainWindow", "16"))
		item = self.tableWidget_4.verticalHeaderItem(16)
		item.setText(_translate("MainWindow", "17"))
		item = self.tableWidget_4.verticalHeaderItem(17)
		item.setText(_translate("MainWindow", "18"))
		item = self.tableWidget_4.verticalHeaderItem(18)
		item.setText(_translate("MainWindow", "19"))
		item = self.tableWidget_4.verticalHeaderItem(19)
		item.setText(_translate("MainWindow", "20"))
		item = self.tableWidget_4.verticalHeaderItem(20)
		item.setText(_translate("MainWindow", "21"))
		item = self.tableWidget_4.verticalHeaderItem(21)
		item.setText(_translate("MainWindow", "22"))
		item = self.tableWidget_4.verticalHeaderItem(22)
		item.setText(_translate("MainWindow", "23"))
		item = self.tableWidget_4.verticalHeaderItem(23)
		item.setText(_translate("MainWindow", "24"))
		item = self.tableWidget_4.verticalHeaderItem(24)
		item.setText(_translate("MainWindow", "25"))
		item = self.tableWidget_4.verticalHeaderItem(25)
		item.setText(_translate("MainWindow", "26"))
		item = self.tableWidget_4.verticalHeaderItem(26)
		item.setText(_translate("MainWindow", "27"))
		item = self.tableWidget_4.verticalHeaderItem(27)
		item.setText(_translate("MainWindow", "28"))
		item = self.tableWidget_4.verticalHeaderItem(28)
		item.setText(_translate("MainWindow", "29"))
		item = self.tableWidget_4.verticalHeaderItem(29)
		item.setText(_translate("MainWindow", "30"))
		item = self.tableWidget_4.verticalHeaderItem(30)
		item.setText(_translate("MainWindow", "31"))
		item = self.tableWidget_4.verticalHeaderItem(31)
		item.setText(_translate("MainWindow", "32"))
		item = self.tableWidget_4.verticalHeaderItem(32)
		item.setText(_translate("MainWindow", "33"))
		item = self.tableWidget_4.verticalHeaderItem(33)
		item.setText(_translate("MainWindow", "35"))
		item = self.tableWidget_4.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "姓名"))
		item = self.tableWidget_4.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "职务"))
		item = self.tableWidget_4.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "基本工资"))
		item = self.tableWidget_4.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "考勤扣除"))
		item = self.tableWidget_4.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "实发工资"))
		__sortingEnabled = self.tableWidget_4.isSortingEnabled()
		self.tableWidget_4.setSortingEnabled(False)
		item = self.tableWidget_4.item(0, 0)
		item.setText(_translate("MainWindow", "显示导入的excel表内容"))
		self.tableWidget_4.setSortingEnabled(__sortingEnabled)
		self.pushButton_2.setText(_translate("MainWindow", "提交"))
		self.groupBox_12.setTitle(_translate("MainWindow", "留言"))
		self.label_22.setText(_translate("MainWindow", "留言内容："))
		self.label_23.setText(_translate("MainWindow", "回复内容："))
		self.label_16.setText(_translate("MainWindow", "处理状态："))
		self.comboBox_4.setItemText(0, _translate("MainWindow", "全部"))
		self.comboBox_4.setItemText(1, _translate("MainWindow", "已回复"))
		self.comboBox_4.setItemText(2, _translate("MainWindow", "未回复"))
		self.label_17.setText(_translate("MainWindow", "留言时间："))
		self.comboBox_6.setItemText(0, _translate("MainWindow", "3月份"))
		self.comboBox_6.setItemText(1, _translate("MainWindow", "4月份"))
		self.comboBox_6.setItemText(2, _translate("MainWindow", "5月份"))
		item = self.tableWidget_5.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "员工姓名"))
		item = self.tableWidget_5.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "员工编号"))
		item = self.tableWidget_5.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "留言内容"))
		item = self.tableWidget_5.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "留言时间"))
		item = self.tableWidget_5.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "处理状态"))
		item = self.tableWidget_5.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "回复内容"))
		item = self.tableWidget_5.horizontalHeaderItem(6)
		item.setText(_translate("MainWindow", "回复时间"))
		item = self.tableWidget_5.horizontalHeaderItem(7)
		item.setText(_translate("MainWindow", "操作"))
		self.groupBox_9.setTitle(_translate("MainWindow", "XXX公司"))
		self.label_54.setText(_translate("MainWindow", "员工工资调整记录表"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "编号"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "姓名"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "部门"))
		item = self.tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "原工资"))
		item = self.tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "调整后"))
		item = self.tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "涨幅"))
		item = self.tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("MainWindow", "操作时间"))
		item = self.tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("MainWindow", "生效时间"))
		__sortingEnabled = self.tableWidget.isSortingEnabled()
		self.tableWidget.setSortingEnabled(False)
		item = self.tableWidget.item(0, 0)
		item.setText(_translate("MainWindow", "不可编辑"))
		self.tableWidget.setSortingEnabled(__sortingEnabled)
		self.groupBox.setTitle(_translate("MainWindow", "修改密码"))
		self.label_8.setText(_translate("MainWindow", "原密码："))
		self.label_12.setText(_translate("MainWindow", "新密码："))
		self.label_20.setText(_translate("MainWindow", "确认密码："))
		self.okButton.setText(_translate("MainWindow", "确定"))
		self.groupBox_19.setTitle(_translate("MainWindow", "权限控制"))
		self.label_25.setText(_translate("MainWindow", "员工编号："))
		self.pushButton_3.setText(_translate("MainWindow", "修改"))
		self.pushButton_4.setText(_translate("MainWindow", "只读"))
		self.groupBox_20.setTitle(_translate("MainWindow", "系统记录"))
		item = self.tableWidget_6.verticalHeaderItem(0)
		item.setText(_translate("MainWindow", "1"))
		item = self.tableWidget_6.verticalHeaderItem(1)
		item.setText(_translate("MainWindow", "2"))
		item = self.tableWidget_6.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "时间"))
		item = self.tableWidget_6.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "对象"))
		item = self.tableWidget_6.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "操作"))
		__sortingEnabled = self.tableWidget_6.isSortingEnabled()
		self.tableWidget_6.setSortingEnabled(False)
		item = self.tableWidget_6.item(0, 0)
		item.setText(_translate("MainWindow", "15:13"))
		item = self.tableWidget_6.item(0, 1)
		item.setText(_translate("MainWindow", "XXX"))
		item = self.tableWidget_6.item(0, 2)
		item.setText(_translate("MainWindow", "提交"))
		item = self.tableWidget_6.item(1, 0)
		item.setText(_translate("MainWindow", "15:16"))
		item = self.tableWidget_6.item(1, 1)
		item.setText(_translate("MainWindow", "XXX"))
		item = self.tableWidget_6.item(1, 2)
		item.setText(_translate("MainWindow", "删除"))
		self.tableWidget_6.setSortingEnabled(__sortingEnabled)
		self.pushButton_8.setText(_translate("MainWindow", "添加"))
		self.pushButton_9.setText(_translate("MainWindow", "清空"))
		self.groupBox_3.setTitle(_translate("MainWindow", "XXX公司"))
		self.label_38.setText(_translate("MainWindow", "员工信息"))
		self.radioButton.setText(_translate("MainWindow", "男"))
		self.radioButton_2.setText(_translate("MainWindow", "女"))
		self.label_45.setText(_translate("MainWindow", "部门："))
		self.label_68.setText(_translate("MainWindow", "家庭住址："))
		self.comboBox_8.setItemText(0, _translate("MainWindow", "财务部"))
		self.comboBox_8.setItemText(1, _translate("MainWindow", "后勤部"))
		self.comboBox_8.setItemText(2, _translate("MainWindow", "人事部"))
		self.comboBox_8.setItemText(3, _translate("MainWindow", "品管部"))
		self.comboBox_8.setItemText(4, _translate("MainWindow", "营销部"))
		self.comboBox_8.setItemText(5, _translate("MainWindow", "产品开发部"))
		self.comboBox_8.setItemText(6, _translate("MainWindow", "人力资源部"))
		self.comboBox_8.setItemText(7, _translate("MainWindow", "资源采购部"))
		self.comboBox_8.setItemText(8, _translate("MainWindow", "售后服务部"))
		self.label_7.setText(_translate("MainWindow", "入职时间："))
		self.label_64.setText(_translate("MainWindow", "职务："))
		self.comboBox_10.setItemText(0, _translate("MainWindow", "文员"))
		self.comboBox_10.setItemText(1, _translate("MainWindow", "生产员工"))
		self.comboBox_10.setItemText(2, _translate("MainWindow", "技术工人"))
		self.comboBox_10.setItemText(3, _translate("MainWindow", "高级工程师"))
		self.comboBox_10.setItemText(4, _translate("MainWindow", "部门经理"))
		self.comboBox_10.setItemText(5, _translate("MainWindow", "主任"))
		self.comboBox_10.setItemText(6, _translate("MainWindow", "总经理"))
		self.label_5.setToolTip(_translate("MainWindow", "点击上传头像"))
		self.label_63.setText(_translate("MainWindow", "学历："))
		self.comboBox_2.setItemText(0, _translate("MainWindow", "本科"))
		self.comboBox_2.setItemText(1, _translate("MainWindow", "专科"))
		self.comboBox_2.setItemText(2, _translate("MainWindow", "小学"))
		self.comboBox_2.setItemText(3, _translate("MainWindow", "初中"))
		self.comboBox_2.setItemText(4, _translate("MainWindow", "研究生"))
		self.comboBox_2.setItemText(5, _translate("MainWindow", "硕士生"))
		self.comboBox_2.setItemText(6, _translate("MainWindow", "博士"))
		self.comboBox_2.setItemText(7, _translate("MainWindow", "博士后"))
		self.label_4.setText(_translate("MainWindow", "性别："))
		self.label_48.setText(_translate("MainWindow", "电话："))
		self.label_44.setText(_translate("MainWindow", "密码："))
		self.label_62.setText(_translate("MainWindow", "身份证："))
		self.label_69.setText(_translate("MainWindow", "毕业学校："))
		self.label_41.setText(_translate("MainWindow", "编号："))
		self.label_55.setText(_translate("MainWindow", "姓名："))
		self.label_9.setText(_translate("MainWindow", "年"))
		self.label_10.setText(_translate("MainWindow", "月"))
		self.label_11.setText(_translate("MainWindow", "日"))
		self.label_37.setText(_translate("MainWindow", "个人简介："))
		self.plainTextEdit_4.setPlainText(_translate("MainWindow", "做为一名传统的中国大学生，我具备了中国人诚实不屈的传统品格，同样的我也具有能被社会所认可的诚信。为了生存我有着奋发向上的追求生活的信念， 在残酷的竞争中，我具备良好的团队合作精神和坚忍不拔的性格。相信自己能在社会中乘风破浪，在广阔的世界畅想遨游。"))
		self.function_menu.setToolTip(_translate("MainWindow", "点击展开或收缩菜单"))
		self.function_menu.setText(_translate("MainWindow", "功能菜单"))



# 通过重载事件实现可点击的Label控件
class ClickedLabel(QtWidgets.QLabel):
	def __init__(self, mainwindow, parent=None):
		super(ClickedLabel, self).__init__(parent)
		self.mainwindow = mainwindow
		
	def mousePressEvent(self, event):
		if event.button() == QtCore.Qt.LeftButton:
			text = self.text()
			if text == '功能菜单':
				if self.mainwindow.is_expanded == False:
					self.mainwindow.treeWidget.expandAll()
					self.mainwindow.is_expanded = True
				else:
					self.mainwindow.treeWidget.collapseAll()
					self.mainwindow.is_expanded = False
			elif text == '您有一条新消息！':
				self.mainwindow.stackedWidget.setCurrentIndex(5)
			elif '当前账户' in text:
				reply = QMessageBox.question(self, '提示', '确认切换账户?', QMessageBox.Yes | QMessageBox.No)
				if reply == QMessageBox.Yes:
					self.mainwindow.hide()
					self.mainwindow.parent().show()

import images_rc


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

