# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Eric6_Workspace\table.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_16 = QtWidgets.QGroupBox(Form)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_58 = QtWidgets.QLabel(self.groupBox_16)
        self.label_58.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_20.addWidget(self.label_58)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_16)
        self.tableWidget_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_3.setTabKeyNavigation(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(14)
        self.tableWidget_3.setRowCount(33)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        self.verticalLayout_20.addWidget(self.tableWidget_3)
        self.info_form_page_bar = QtWidgets.QWidget(self.groupBox_16)
        self.info_form_page_bar.setObjectName("info_form_page_bar")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.info_form_page_bar)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.info_form_first_page = QtWidgets.QPushButton(self.info_form_page_bar)
        self.info_form_first_page.setObjectName("info_form_first_page")
        self.horizontalLayout_21.addWidget(self.info_form_first_page)
        self.info_form_previous_page = QtWidgets.QPushButton(self.info_form_page_bar)
        self.info_form_previous_page.setObjectName("info_form_previous_page")
        self.horizontalLayout_21.addWidget(self.info_form_previous_page)
        self.info_form_page_num = QtWidgets.QLabel(self.info_form_page_bar)
        self.info_form_page_num.setAlignment(QtCore.Qt.AlignCenter)
        self.info_form_page_num.setObjectName("info_form_page_num")
        self.horizontalLayout_21.addWidget(self.info_form_page_num)
        self.info_form_next_page = QtWidgets.QPushButton(self.info_form_page_bar)
        self.info_form_next_page.setObjectName("info_form_next_page")
        self.horizontalLayout_21.addWidget(self.info_form_next_page)
        self.info_form_last_page = QtWidgets.QPushButton(self.info_form_page_bar)
        self.info_form_last_page.setObjectName("info_form_last_page")
        self.horizontalLayout_21.addWidget(self.info_form_last_page)
        self.verticalLayout_20.addWidget(self.info_form_page_bar)
        self.verticalLayout.addWidget(self.groupBox_16)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_16.setTitle(_translate("Form", "XXX公司"))
        self.label_58.setText(_translate("Form", "员工信息表"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_3.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_3.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_3.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_3.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_3.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_3.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_3.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget_3.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_3.verticalHeaderItem(22)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget_3.verticalHeaderItem(23)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_3.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget_3.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget_3.verticalHeaderItem(26)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget_3.verticalHeaderItem(27)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget_3.verticalHeaderItem(28)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_3.verticalHeaderItem(29)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget_3.verticalHeaderItem(30)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget_3.verticalHeaderItem(31)
        item.setText(_translate("Form", "33"))
        item = self.tableWidget_3.verticalHeaderItem(32)
        item.setText(_translate("Form", "35"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "性别"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "部门"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "密码"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "电话"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("Form", "学历"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("Form", "职务"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("Form", "照片"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("Form", "身份证"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("Form", "入职时间"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("Form", "毕业学校"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("Form", "家庭住址"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("Form", "个人简介"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Form", "不可编辑"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.info_form_first_page.setText(_translate("Form", "首页"))
        self.info_form_previous_page.setText(_translate("Form", "上一页"))
        self.info_form_page_num.setText(_translate("Form", "[50/200]页"))
        self.info_form_next_page.setText(_translate("Form", "下一页"))
        self.info_form_last_page.setText(_translate("Form", "尾页"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

