# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Eric6_Workspace\widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 800)
        Form.setStyleSheet("")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.graphicsView_2.setStyleSheet("background-color: rgb(99, 167, 255);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_3.addWidget(self.graphicsView_2, 0, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setStyleSheet("background-color: rgb(107, 255, 66);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.page)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_14)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_14)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_14, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setSpacing(21)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_10.addWidget(self.label_38)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(21)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinBox = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox.setMinimum(2017)
        self.spinBox.setMaximum(2050)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_9.addWidget(self.spinBox)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_9.addWidget(self.spinBox_2)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(31)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_9.addWidget(self.spinBox_3)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.gridLayout_2.addWidget(self.widget_5, 6, 1, 1, 2)
        self.label_41 = QtWidgets.QLabel(self.widget_4)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 0, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.widget_4)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 0, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 0, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.widget_4)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 5, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_2.addWidget(self.lineEdit_33, 7, 1, 1, 4)
        self.label_69 = QtWidgets.QLabel(self.widget_4)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_2.addWidget(self.label_69, 7, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.widget_4)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_2.addWidget(self.label_68, 8, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_8.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox_8.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_8, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget_4)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 3, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.widget_4)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 3, 2, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_2.addWidget(self.lineEdit_40, 8, 1, 1, 4)
        self.comboBox_10 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_10.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox_10.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_10, 3, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_25.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_25.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 5, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.widget_4)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 2, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_35.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_35.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_2.addWidget(self.lineEdit_35, 2, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_24.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 1, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_4)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.widget_4)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 2, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_2.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setStyleSheet("border: 1px solid rgb(173, 173, 173);")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/profile_picture.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setMargin(3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 4, 1)
        self.verticalLayout_10.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_37 = QtWidgets.QLabel(self.widget_6)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_5.addWidget(self.label_37)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.widget_6)
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.plainTextEdit_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.verticalLayout_5.addWidget(self.plainTextEdit_4)
        self.verticalLayout_10.addWidget(self.widget_6)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_21 = QtWidgets.QWidget(self.page_7)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_14 = QtWidgets.QGroupBox(self.widget_21)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox_14)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setMaxCount(12)
        self.comboBox_5.setFrame(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_5)
        self.label_20 = QtWidgets.QLabel(self.groupBox_14)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_19.addWidget(self.pushButton_25)
        self.horizontalLayout_18.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget_21)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_38.setFrame(True)
        self.lineEdit_38.setClearButtonEnabled(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_20.addWidget(self.lineEdit_38)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_20.addWidget(self.pushButton_26)
        self.horizontalLayout_18.addWidget(self.groupBox_15)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 3)
        self.gridLayout_5.addWidget(self.widget_21, 0, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.page_7)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_58 = QtWidgets.QLabel(self.groupBox_16)
        self.label_58.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_20.addWidget(self.label_58)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_16)
        self.tableWidget_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_3.setTabKeyNavigation(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(15)
        self.tableWidget_3.setRowCount(33)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        self.verticalLayout_20.addWidget(self.tableWidget_3)
        self.widget_22 = QtWidgets.QWidget(self.groupBox_16)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_27 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_21.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_21.addWidget(self.pushButton_28)
        self.label_21 = QtWidgets.QLabel(self.widget_22)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_21.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_21.addWidget(self.pushButton_30)
        self.verticalLayout_20.addWidget(self.widget_22)
        self.gridLayout_5.addWidget(self.groupBox_16, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox.setEditable(True)
        self.comboBox.setMaxCount(12)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_31.setFrame(True)
        self.lineEdit_31.setClearButtonEnabled(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_6.addWidget(self.lineEdit_31)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_53 = QtWidgets.QLabel(self.groupBox_8)
        self.label_53.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.verticalLayout.addWidget(self.label_53)
        self.tableView = QtWidgets.QTableView(self.groupBox_8)
        self.tableView.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_8)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_3.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_3.addWidget(self.pushButton_16)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.page_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setMaxCount(12)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_3)
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_12.addWidget(self.pushButton_17)
        self.horizontalLayout_11.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_34.setFrame(True)
        self.lineEdit_34.setClearButtonEnabled(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_13.addWidget(self.lineEdit_34)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_13.addWidget(self.pushButton_18)
        self.horizontalLayout_11.addWidget(self.groupBox_11)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_51 = QtWidgets.QLabel(self.groupBox_4)
        self.label_51.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_4.addWidget(self.label_51)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_2.setTabKeyNavigation(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(33)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.widget_12 = QtWidgets.QWidget(self.page_3)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_14.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_14.addWidget(self.pushButton_20)
        self.label_15 = QtWidgets.QLabel(self.widget_12)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_14.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_14.addWidget(self.pushButton_22)
        self.verticalLayout_7.addWidget(self.widget_12)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_54 = QtWidgets.QLabel(self.groupBox_9)
        self.label_54.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_12.addWidget(self.label_54)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_9)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget.setRowCount(14)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        self.verticalLayout_12.addWidget(self.tableWidget)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_52 = QtWidgets.QLabel(self.groupBox_7)
        self.label_52.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_9.addWidget(self.label_52)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableWidget_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_4.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(34)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        self.verticalLayout_9.addWidget(self.tableWidget_4)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_6)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.gridLayout_4.addWidget(self.groupBox, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(298, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(366, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 3, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.page_6)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(67, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.okButton = QtWidgets.QPushButton(self.widget_9)
        self.okButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okButton.setAutoDefault(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_10.addWidget(self.okButton)
        spacerItem12 = QtWidgets.QSpacerItem(79, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_9)
        self.btn_cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_10.addWidget(self.btn_cancel)
        spacerItem13 = QtWidgets.QSpacerItem(79, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.gridLayout_4.addWidget(self.widget_9, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout_3.addWidget(self.frame, 2, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.662, y1:0.017, x2:0.417, y2:1, stop:0 rgba(0, 191, 82, 255), stop:1 rgba(255, 255, 255, 255));")
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_3.addWidget(self.treeWidget, 2, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 5)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(4)
        self.comboBox.setCurrentIndex(4)
        self.comboBox_3.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_25.setText(_translate("Form", "消息提醒（滚动条）"))
        self.pushButton_8.setText(_translate("Form", "添加"))
        self.pushButton_9.setText(_translate("Form", "重置"))
        self.groupBox_3.setTitle(_translate("Form", "XXX公司"))
        self.label_38.setText(_translate("Form", "员工信息"))
        self.label_9.setText(_translate("Form", "年"))
        self.label_10.setText(_translate("Form", "月"))
        self.label_11.setText(_translate("Form", "日"))
        self.label_41.setText(_translate("Form", "编号："))
        self.label_55.setText(_translate("Form", "姓名："))
        self.label_62.setText(_translate("Form", "身份证："))
        self.label_69.setText(_translate("Form", "毕业学校："))
        self.label_68.setText(_translate("Form", "家庭住址："))
        self.comboBox_8.setItemText(0, _translate("Form", "财务部"))
        self.comboBox_8.setItemText(1, _translate("Form", "后勤部"))
        self.comboBox_8.setItemText(2, _translate("Form", "人事部"))
        self.comboBox_8.setItemText(3, _translate("Form", "品管部"))
        self.comboBox_8.setItemText(4, _translate("Form", "营销部"))
        self.comboBox_8.setItemText(5, _translate("Form", "产品开发部"))
        self.comboBox_8.setItemText(6, _translate("Form", "人力资源部"))
        self.comboBox_8.setItemText(7, _translate("Form", "资源采购部"))
        self.comboBox_8.setItemText(8, _translate("Form", "售后服务部"))
        self.label_7.setText(_translate("Form", "入职时间："))
        self.label_45.setText(_translate("Form", "部门："))
        self.label_64.setText(_translate("Form", "职务："))
        self.comboBox_10.setItemText(0, _translate("Form", "文员"))
        self.comboBox_10.setItemText(1, _translate("Form", "生产员工"))
        self.comboBox_10.setItemText(2, _translate("Form", "技术工人"))
        self.comboBox_10.setItemText(3, _translate("Form", "高级工程师"))
        self.comboBox_10.setItemText(4, _translate("Form", "部门经理"))
        self.comboBox_10.setItemText(5, _translate("Form", "主任"))
        self.comboBox_10.setItemText(6, _translate("Form", "总经理"))
        self.label_48.setText(_translate("Form", "电话："))
        self.label_44.setText(_translate("Form", "密码："))
        self.label_4.setText(_translate("Form", "性别："))
        self.radioButton.setText(_translate("Form", "男"))
        self.radioButton_2.setText(_translate("Form", "女"))
        self.label_63.setText(_translate("Form", "学历："))
        self.comboBox_2.setItemText(0, _translate("Form", "本科"))
        self.comboBox_2.setItemText(1, _translate("Form", "专科"))
        self.comboBox_2.setItemText(2, _translate("Form", "小学"))
        self.comboBox_2.setItemText(3, _translate("Form", "初中"))
        self.comboBox_2.setItemText(4, _translate("Form", "研究生"))
        self.comboBox_2.setItemText(5, _translate("Form", "硕士生"))
        self.comboBox_2.setItemText(6, _translate("Form", "博士"))
        self.comboBox_2.setItemText(7, _translate("Form", "博士后"))
        self.label_37.setText(_translate("Form", "个人简介："))
        self.plainTextEdit_4.setPlainText(_translate("Form", "做为一名传统的中国大学生，我具备了中国人诚实不屈的传统品格，同样的我也具有能被社会所认可的诚信。为了生存我有着奋发向上的追求生活的信念， 在残酷的竞争中，我具备良好的团队合作精神和坚忍不拔的性格。相信自己能在社会中乘风破浪，在广阔的世界畅想遨游。"))
        self.groupBox_14.setTitle(_translate("Form", "日期查询"))
        self.label_19.setText(_translate("Form", "2019年"))
        self.comboBox_5.setItemText(0, _translate("Form", "2"))
        self.comboBox_5.setItemText(1, _translate("Form", "3"))
        self.comboBox_5.setItemText(2, _translate("Form", "4"))
        self.comboBox_5.setItemText(3, _translate("Form", "11"))
        self.comboBox_5.setItemText(4, _translate("Form", "12"))
        self.label_20.setText(_translate("Form", "月"))
        self.pushButton_25.setText(_translate("Form", "查询"))
        self.groupBox_15.setTitle(_translate("Form", "关键词搜索"))
        self.lineEdit_38.setPlaceholderText(_translate("Form", "模糊查询"))
        self.pushButton_26.setText(_translate("Form", "查询"))
        self.groupBox_16.setTitle(_translate("Form", "XXX公司"))
        self.label_58.setText(_translate("Form", "员工信息表"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_3.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_3.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_3.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_3.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_3.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_3.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_3.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget_3.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_3.verticalHeaderItem(22)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget_3.verticalHeaderItem(23)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_3.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget_3.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget_3.verticalHeaderItem(26)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget_3.verticalHeaderItem(27)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget_3.verticalHeaderItem(28)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_3.verticalHeaderItem(29)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget_3.verticalHeaderItem(30)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget_3.verticalHeaderItem(31)
        item.setText(_translate("Form", "33"))
        item = self.tableWidget_3.verticalHeaderItem(32)
        item.setText(_translate("Form", "35"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "性别"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "部门"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "密码"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "电话"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("Form", "学历"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("Form", "部门"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("Form", "职务"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("Form", "照片"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("Form", "身份证"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("Form", "入职时间"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("Form", "毕业学校"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("Form", "家庭住址"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("Form", "个人简介"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Form", "不可编辑"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_27.setText(_translate("Form", "首页"))
        self.pushButton_28.setText(_translate("Form", "上一页"))
        self.label_21.setText(_translate("Form", "[50/200]页"))
        self.pushButton_29.setText(_translate("Form", "下一页"))
        self.pushButton_30.setText(_translate("Form", "尾页"))
        self.groupBox_2.setTitle(_translate("Form", "日期查询"))
        self.label_2.setText(_translate("Form", "2019年"))
        self.comboBox.setItemText(0, _translate("Form", "2"))
        self.comboBox.setItemText(1, _translate("Form", "3"))
        self.comboBox.setItemText(2, _translate("Form", "4"))
        self.comboBox.setItemText(3, _translate("Form", "11"))
        self.comboBox.setItemText(4, _translate("Form", "12"))
        self.label_3.setText(_translate("Form", "月"))
        self.pushButton_12.setText(_translate("Form", "查询"))
        self.groupBox_5.setTitle(_translate("Form", "关键词搜索"))
        self.lineEdit_31.setPlaceholderText(_translate("Form", "模糊查询"))
        self.pushButton_10.setText(_translate("Form", "查询"))
        self.groupBox_8.setTitle(_translate("Form", "XXX公司"))
        self.label_53.setText(_translate("Form", "员工工资表"))
        self.pushButton_5.setText(_translate("Form", "首页"))
        self.pushButton_14.setText(_translate("Form", "上一页"))
        self.label.setText(_translate("Form", "[3/200]页"))
        self.pushButton_15.setText(_translate("Form", "下一页"))
        self.pushButton_16.setText(_translate("Form", "尾页"))
        self.groupBox_10.setTitle(_translate("Form", "日期查询"))
        self.label_13.setText(_translate("Form", "2019年"))
        self.comboBox_3.setItemText(0, _translate("Form", "2"))
        self.comboBox_3.setItemText(1, _translate("Form", "3"))
        self.comboBox_3.setItemText(2, _translate("Form", "4"))
        self.comboBox_3.setItemText(3, _translate("Form", "11"))
        self.comboBox_3.setItemText(4, _translate("Form", "12"))
        self.label_14.setText(_translate("Form", "月"))
        self.pushButton_17.setText(_translate("Form", "查询"))
        self.groupBox_11.setTitle(_translate("Form", "关键词搜索"))
        self.lineEdit_34.setPlaceholderText(_translate("Form", "模糊查询"))
        self.pushButton_18.setText(_translate("Form", "查询"))
        self.groupBox_4.setTitle(_translate("Form", "XXX公司"))
        self.label_51.setText(_translate("Form", "员工考勤表"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget_2.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget_2.verticalHeaderItem(26)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget_2.verticalHeaderItem(27)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget_2.verticalHeaderItem(28)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_2.verticalHeaderItem(29)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget_2.verticalHeaderItem(30)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget_2.verticalHeaderItem(31)
        item.setText(_translate("Form", "33"))
        item = self.tableWidget_2.verticalHeaderItem(32)
        item.setText(_translate("Form", "35"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "部门"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "迟到"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "早退"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "病假"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "事假"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Form", "旷工"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "不可编辑"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_19.setText(_translate("Form", "首页"))
        self.pushButton_20.setText(_translate("Form", "上一页"))
        self.label_15.setText(_translate("Form", "[50/200]页"))
        self.pushButton_21.setText(_translate("Form", "下一页"))
        self.pushButton_22.setText(_translate("Form", "尾页"))
        self.groupBox_9.setTitle(_translate("Form", "XXX公司"))
        self.label_54.setText(_translate("Form", "员工工资调整记录表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "部门"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "原工资"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "调整后"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "涨幅"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "操作时间"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "生效时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "不可编辑"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(_translate("Form", "Excel相关操作"))
        self.pushButton_6.setText(_translate("Form", "导入Excel表"))
        self.pushButton_7.setText(_translate("Form", "导出Excel表"))
        self.pushButton_13.setText(_translate("Form", "打印"))
        self.groupBox_7.setTitle(_translate("Form", "XXX公司"))
        self.label_52.setText(_translate("Form", "员工工资表"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_4.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_4.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_4.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_4.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_4.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_4.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_4.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_4.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_4.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_4.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget_4.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_4.verticalHeaderItem(22)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_4.verticalHeaderItem(23)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget_4.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget_4.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget_4.verticalHeaderItem(26)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget_4.verticalHeaderItem(27)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget_4.verticalHeaderItem(28)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget_4.verticalHeaderItem(29)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_4.verticalHeaderItem(30)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget_4.verticalHeaderItem(31)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget_4.verticalHeaderItem(32)
        item.setText(_translate("Form", "33"))
        item = self.tableWidget_4.verticalHeaderItem(33)
        item.setText(_translate("Form", "35"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "职务"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "基本工资"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "考勤扣除"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "实发工资"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("Form", "可编辑"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Form", "修改密码"))
        self.label_8.setText(_translate("Form", "原密码："))
        self.label_12.setText(_translate("Form", "新密码："))
        self.okButton.setText(_translate("Form", "确定"))
        self.btn_cancel.setText(_translate("Form", "取消"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "功能菜单"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "员工管理"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "查询"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "修改"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "考勤管理"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "查询"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "修改"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "工资管理"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Form", "查询"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Form", "修改"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Form", "调整记录"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "留言管理"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Form", "新消息"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Form", "消息记录"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "系统管理"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Form", "修改密码"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Form", "操作记录"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Form", "注销账号"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("Form", "退出系统"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

